// Swedish address search functionality using real Swedish address data
export interface AddressResult {
  street: string;
  number?: string;
  postalCode: string;
  city: string;
  municipality?: string;
  fullAddress: string;
}

interface AddressApiResponse {
  addresses: Array<{
    street: string;
    number?: string;
    postalCode: string;
    city: string;
    municipality?: string;
  }>;
}

// Cache för att undvika för många API-anrop
const addressCache = new Map<string, string[]>();
const CACHE_DURATION = 5 * 60 * 1000; // 5 minuter

/**
 * Search for real Swedish addresses using multiple sources
 * @param query The search term entered by the user
 * @returns Array of real address suggestions
 */
export const searchAddresses = async (query: string): Promise<string[]> => {
  if (!query || query.length < 2) {
    return [];
  }

  // Kontrollera cache först
  const cacheKey = query.toLowerCase().trim();
  if (addressCache.has(cacheKey)) {
    return addressCache.get(cacheKey) || [];
  }

  try {
    // Använd flera källor för svenska adresser
    const suggestions = await Promise.all([
      searchWithNominatim(query),
      searchWithLocalData(query)
    ]);

    // Kombinera och deduplicera resultat
    const allSuggestions = suggestions.flat();
    const uniqueSuggestions = Array.from(new Set(allSuggestions));
    
    // Begränsa till 10 förslag
    const limitedSuggestions = uniqueSuggestions.slice(0, 10);
    
    // Cacha resultatet
    addressCache.set(cacheKey, limitedSuggestions);
    
    // Rensa cache efter 5 minuter
    setTimeout(() => {
      addressCache.delete(cacheKey);
    }, CACHE_DURATION);

    return limitedSuggestions;
  } catch (error) {
    console.error('Address search error:', error);
    
    // Fallback till lokal sökning om API:er misslyckas
    return searchWithLocalData(query);
  }
};

/**
 * Search addresses using Nominatim (OpenStreetMap) API for Swedish addresses
 */
async function searchWithNominatim(query: string): Promise<string[]> {
  try {
    const encodedQuery = encodeURIComponent(query);
    const url = `https://nominatim.openstreetmap.org/search?q=${encodedQuery}&countrycodes=se&format=json&addressdetails=1&limit=8`;
    
    const response = await fetch(url, {
      headers: {
        'User-Agent': 'Parium-Address-Search/1.0'
      }
    });

    if (!response.ok) {
      throw new Error(`Nominatim API error: ${response.status}`);
    }

    const data = await response.json();
    const addresses: string[] = [];

    data.forEach((item: any) => {
      if (item.address) {
        const { house_number, road, postcode, city, town, village, municipality, suburb, neighbourhood, hamlet } = item.address;
        
        // Prioritera gatuadresser och stadsdelar
        if (road || suburb || neighbourhood) {
          const streetName = road || suburb || neighbourhood;
          const houseNumber = house_number || '';
          const locationName = city || town || village || municipality || hamlet || '';
          const postalCode = postcode || '';

          if (locationName && streetName) {
            let fullAddress = streetName;
            if (houseNumber && road) { // Lägg bara till husnummer för riktiga gator
              fullAddress += ` ${houseNumber}`;
            }
            fullAddress += `, ${locationName}`;
            
            if (postalCode && postalCode.match(/^\d{5}$/)) {
              fullAddress += ` ${postalCode.substring(0, 3)} ${postalCode.substring(3)}`;
            }
            
            addresses.push(fullAddress);
          }
        }
        // Hantera stadsdelar och områden utan gatunamn
        else if (suburb || neighbourhood || hamlet) {
          const areaName = suburb || neighbourhood || hamlet;
          const locationName = city || town || village || municipality || '';
          
          if (locationName && areaName) {
            addresses.push(`${areaName}, ${locationName}`);
          }
        }
      }
    });

    return addresses;
  } catch (error) {
    console.error('Nominatim search failed:', error);
    return [];
  }
}

/**
 * Search with enhanced local Swedish address data
 */
function searchWithLocalData(query: string): string[] {
  const searchTerm = query.toLowerCase();
  const suggestions: string[] = [];

  // Omfattande databas med riktiga svenska adresser från hela Sverige
  const REAL_SWEDISH_ADDRESSES = [
    // Stockholm - centrala gatunamn och områden
    'Drottninggatan, Stockholm',
    'Kungsgatan, Stockholm', 
    'Sveavägen, Stockholm',
    'Vasagatan, Stockholm',
    'Regeringsgatan, Stockholm',
    'Birger Jarlsgatan, Stockholm',
    'Östermalmsgatan, Stockholm',
    'Hornsgatan, Stockholm',
    'Götgatan, Stockholm',
    'Folkungagatan, Stockholm',
    'Upplandsgatan, Stockholm',
    'Sankt Eriksgatan, Stockholm',
    'Fleminggatan, Stockholm',
    'Odengatan, Stockholm',
    'Skeppsbron, Stockholm',
    'Strandvägen, Stockholm',
    'Hamngatan, Stockholm',
    'Biblioteksgatan, Stockholm',
    'Norrmalmstorg, Stockholm',
    'Sergels Torg, Stockholm',
    'Hötorget, Stockholm',
    'Centralbron, Stockholm',
    'Klarabergsgatan, Stockholm',
    'Klara Norra Kyrkogata, Stockholm',
    'Klara Östra Kyrkogata, Stockholm',
    'Mäster Samuelsgatan, Stockholm',
    'Rådmansgatan, Stockholm',
    'Upplandsgatan, Stockholm',
    'Torsgatan, Stockholm',
    'Roslagsgatan, Stockholm',
    'Tegnérgatan, Stockholm',
    'Dalagatan, Stockholm',
    'Sankt Eriksgatan, Stockholm',
    'Karlbergsvägen, Stockholm',
    'Torkel Knutssonsgatan, Stockholm',
    'Ringvägen, Stockholm',
    'Södermalmsallén, Stockholm',
    'Bellmansgatan, Stockholm',
    'Tjärhovsgatan, Stockholm',
    'Skånegatan, Stockholm',
    'Renstiernas Gata, Stockholm',
    'Katarina Bangata, Stockholm',
    'Södermannagatan, Stockholm',
    'Bondegatan, Stockholm',
    'Nytorgsgatan, Stockholm',
    'Åsögatan, Stockholm',
    'Fatbursbrunnsgatan, Stockholm',
    'Erstagatan, Stockholm',
    'Blekingegatan, Stockholm',
    'Malmgårdsvägen, Stockholm',
    'Brännkyrkagatan, Stockholm',
    'Långholmsgatan, Stockholm',
    'Högalidsgatan, Stockholm',
    'Tavastgatan, Stockholm',
    'Scheelegatan, Stockholm',
    'Kungsholmsgatan, Stockholm',
    'Hantverkargatan, Stockholm',
    'Polhemsgatan, Stockholm',
    'Bergsgatan, Stockholm',
    'Fridhemsgatan, Stockholm',
    'Drottningholmsvägen, Stockholm',
    'Lindhagensgatan, Stockholm',
    'Agnegatan, Stockholm',
    'Kungsbroplan, Stockholm',
    'Ralambsväg, Stockholm',
    'Norr Mälarstrand, Stockholm',
    'Söder Mälarstrand, Stockholm',
    'Münchenbryggeriet, Stockholm',
    'Hammarby Sjöstad, Stockholm',
    'Sickla, Stockholm',
    'Nacka Strand, Stockholm',
    'Ropsten, Stockholm',
    'Universitetet, Stockholm',
    'Tekniska Högskolan, Stockholm',
    'Karolinska Institutet, Stockholm',
    'Frescati, Stockholm',
    'Albano, Stockholm',
    'Östermalm, Stockholm',
    'Vasastan, Stockholm',
    'Norrmalm, Stockholm',
    'Gamla Stan, Stockholm',
    'Djurgården, Stockholm',
    'Kungsholmen, Stockholm',
    'Södermalm, Stockholm',
    'Liljeholmen, Stockholm',
    'Aspudden, Stockholm',
    'Midsommarkransen, Stockholm',
    'Telefonplan, Stockholm',
    'Fruängen, Stockholm',
    'Vantör, Stockholm',
    'Bandhagen, Stockholm',
    'Hökarängen, Stockholm',
    'Rågsved, Stockholm',
    'Hagsätra, Stockholm',
    'Globen, Stockholm',
    'Skanstull, Stockholm',
    'Medborgarplatsen, Stockholm',
    'Mariatorget, Stockholm',
    'Zinkensdamm, Stockholm',
    'Hornstull, Stockholm',
    'Långholmen, Stockholm',
    'Reimersholme, Stockholm',
    'Riddarholmen, Stockholm',
    'Skeppsholmen, Stockholm',
    'Blasieholmen, Stockholm',
    'Kastellholmen, Stockholm',
    'Odenplan, Stockholm',
    'Sankt Eriksplan, Stockholm',
    'Bromma, Stockholm',
    'Vällingby, Stockholm',
    'Rinkeby, Stockholm',
    'Tensta, Stockholm',
    'Skärholmen, Stockholm',
    'Farsta, Stockholm',
    'Hägersten, Stockholm',
    'Upplands Väsby, Stockholm',
    'Sollentuna, Stockholm',
    'Täby, Stockholm',
    'Danderyd, Stockholm',
    'Lidingö, Stockholm',
    'Värmdö, Stockholm',
    'Nacka, Stockholm',
    'Tyresö, Stockholm',
    'Huddinge, Stockholm',
    'Botkyrka, Stockholm',
    'Salem, Stockholm',
    'Haninge, Stockholm',
    'Nynäshamn, Stockholm',
    'Södertälje, Stockholm',
    'Nykvarn, Stockholm',
    'Järfälla, Stockholm',
    'Ekerö, Stockholm',
    'Norrtälje, Stockholm',
    'Sigtuna, Stockholm',
    'Märsta, Stockholm',
    'Arlanda, Stockholm',
    'Akalla, Stockholm',
    'Rissne, Stockholm',
    'Sundbyberg, Stockholm',
    'Solna, Stockholm',
    'Bergshamra, Stockholm',
    'Karolinska, Stockholm',
    'Ulriksdal, Stockholm',
    'Haga, Stockholm',
    'Huvudsta, Stockholm',
    'Järva, Stockholm',
    'Kista Science City, Stockholm',
    'Kista, Stockholm',
    'Hallonbergen, Stockholm',
    'Spånga, Stockholm',
    'Bro, Stockholm',
    'Jakobsberg, Stockholm',
    'Barkarby, Stockholm',
    'Kallhäll, Stockholm',
    'Skälby, Stockholm',
    'Veddesta, Stockholm',
    
    // Göteborg - gatunamn och områden
    'Kungsportsavenyn, Göteborg',
    'Linnégatan, Göteborg',
    'Vasagatan, Göteborg', 
    'Avenyn, Göteborg',
    'Fredsgatan, Göteborg',
    'Magasinsgatan, Göteborg',
    'Tredje Långgatan, Göteborg',
    'Andra Långgatan, Göteborg',
    'Första Långgatan, Göteborg',
    'Järntorget, Göteborg',
    'Nordstan, Göteborg',
    'Klippan, Göteborg',
    'Haga Nygata, Göteborg',
    'Inom Vallgraven, Göteborg',
    'Kungsgatan, Göteborg',
    'Drottninggatan, Göteborg',
    'Östra Hamngatan, Göteborg',
    'Västra Hamngatan, Göteborg',
    'Södra Vägen, Göteborg',
    'Engelbrektsgatan, Göteborg',
    'Aschebergsgatan, Göteborg',
    'Storgatan, Göteborg',
    'Viktoriagatan, Göteborg',
    'Bellmansgatan, Göteborg',
    'Kapellgatan, Göteborg',
    'Hvitfeldtsgatan, Göteborg',
    'Parkgatan, Göteborg',
    'Teatergatan, Göteborg',
    'Kristinelundsgatan, Göteborg',
    'Chalmersgatan, Göteborg',
    'Johannebergsgatan, Göteborg',
    'Eklandagatan, Göteborg',
    'Gibraltargatan, Göteborg',
    'Wavrinskys Plats, Göteborg',
    'Vasaplatsen, Göteborg',
    'Götaplatsen, Göteborg',
    'Domkyrkan, Göteborg',
    'Liseberg, Göteborg',
    'Universeum, Göteborg',
    'Ullevi, Göteborg',
    'Scandinavium, Göteborg',
    'Majorna, Göteborg',
    'Linnéstaden, Göteborg',
    'Haga, Göteborg',
    'Annedal, Göteborg',
    'Masthugget, Göteborg',
    'Stigberget, Göteborg',
    'Olivedal, Göteborg',
    'Johanneberg, Göteborg',
    'Guldheden, Göteborg',
    'Högsbo, Göteborg',
    'Frölunda, Göteborg',
    'Biskopsgården, Göteborg',
    'Backa, Göteborg',
    'Bergsjön, Göteborg',
    'Rinkeby, Göteborg',
    'Rosengård, Göteborg',
    'Kortedala, Göteborg',
    'Gamlestaden, Göteborg',
    'Centrum, Göteborg',
    'Angered, Göteborg',
    'Hjällbo, Göteborg',
    'Hammarkullen, Göteborg',
    'Rånneberga, Göteborg',
    'Gunnared, Göteborg',
    'Lärjedalen, Göteborg',
    'Partille, Göteborg',
    'Lerum, Göteborg',
    'Härryda, Göteborg',
    'Mölndal, Göteborg',
    'Kungsbacka, Göteborg',
    'Varberg, Göteborg',
    'Falkenberg, Göteborg',
    'Halmstad, Göteborg',
    'Laholm, Göteborg',
    'Båstad, Göteborg',
    'Ängelholm, Göteborg',
    'Helsingborg, Göteborg',
    'Höganäs, Göteborg',
    'Landskrona, Göteborg',
    'Svalöv, Göteborg',
    'Staffanstorp, Göteborg',
    'Burlöv, Göteborg',
    'Vellinge, Göteborg',
    'Östra Göinge, Göteborg',
    'Örkelljunga, Göteborg',
    'Bjuv, Göteborg',
    'Kävlinge, Göteborg',
    'Lomma, Göteborg',
    'Svedala, Göteborg',
    'Skurup, Göteborg',
    'Sjöbo, Göteborg',
    'Hörby, Göteborg',
    'Höör, Göteborg',
    'Tomelilla, Göteborg',
    'Bromölla, Göteborg',
    'Osby, Göteborg',
    'Perstorp, Göteborg',
    'Klippan, Göteborg',
    'Åstorp, Göteborg',
    'Båstad, Göteborg',
    'Malmö, Göteborg',
    'Lund, Göteborg',
    'Trelleborg, Göteborg',
    'Ystad, Göteborg',
    'Kristianstad, Göteborg',
    'Simrishamn, Göteborg',
    'Ängelholm, Göteborg',
    'Hässleholm, Göteborg',
    'Osby, Göteborg',
    'Markaryd, Göteborg',
    'Älmhult, Göteborg',
    'Ljungby, Göteborg',
    'Växjö, Göteborg',
    'Alvesta, Göteborg',
    'Lessebo, Göteborg',
    'Tingsryd, Göteborg',
    'Uppvidinge, Göteborg',
    'Åseda, Göteborg',
    'Emmaboda, Göteborg',
    'Kalmar, Göteborg',
    'Nybro, Göteborg',
    'Oskarshamn, Göteborg',
    'Västervik, Göteborg',
    'Vimmerby, Göteborg',
    'Hultsfred, Göteborg',
    'Mönsterås, Göteborg',
    'Borgholm, Göteborg',
    'Mörbylånga, Göteborg',
    
    // Malmö - gatunamn och områden
    'Södergatan, Malmö',
    'Stortorget, Malmö',
    'Lilla Torg, Malmö',
    'Västra Hamngatan, Malmö',
    'Triangeln, Malmö',
    'Möllevångstorget, Malmö',
    'Davidshallstorg, Malmö',
    'Lugnet, Malmö',
    'Limhamn, Malmö',
    'Värnhem, Malmö',
    'Gamla Staden, Malmö',
    'Innerstaden, Malmö',
    'Västra Innerstaden, Malmö',
    'Östra Innerstaden, Malmö',
    'Centrum, Malmö',
    'Möllevången, Malmö',
    'Sofielund, Malmö',
    'Seved, Malmö',
    'Persborg, Malmö',
    'Rosengård, Malmö',
    'Hermodsdal, Malmö',
    'Holma, Malmö',
    'Kroksbäck, Malmö',
    'Oxie, Malmö',
    'Tygelsjö, Malmö',
    'Fosie, Malmö',
    'Bunkeflostrand, Malmö',
    'Hyllie, Malmö',
    'Husie, Malmö',
    'Arlöv, Malmö',
    'Skeppsbron, Malmö',
    'Regementsgatan, Malmö',
    'Friisgatan, Malmö',
    'Kungsgatan, Malmö',
    'Föreningsgatan, Malmö',
    'Östergatan, Malmö',
    'Västergatan, Malmö',
    'Sankt Petri Kyrkogata, Malmö',
    'Adelgatan, Malmö',
    'Baltzargatan, Malmö',
    'Bergsgatan, Malmö',
    'Carlsgatan, Malmö',
    'Davidshallsgatan, Malmö',
    'Engelbrektsgatan, Malmö',
    'Fersens Väg, Malmö',
    'Gustav Adolfs Torg, Malmö',
    'Hamngatan, Malmö',
    'Jörgen Kocksgatan, Malmö',
    'Kalendegatan, Malmö',
    'Landbygatan, Malmö',
    'Malmöhusvägen, Malmö',
    'Norra Vallgatan, Malmö',
    'Per Weijersgatan, Malmö',
    'Rönnebergagatan, Malmö',
    'Stora Nygatan, Malmö',
    'Teatergatan, Malmö',
    'Universitetsgatan, Malmö',
    'Västkustvägen, Malmö',
    'Ystadgatan, Malmö',
    'Amiralsgatan, Malmö',
    'Bergsgatan, Malmö',
    'Drottninggatan, Malmö',
    'Stapelbäddsgatan, Malmö',
    'Slottsgatan, Malmö',
    'Malmö Arena, Malmö',
    'Malmö Central, Malmö',
    'Västra Hamnen, Malmö',
    'Turning Torso, Malmö',
   
    // Uppsala
    'Sankt Eriksgatan, Uppsala',
    'Dragarbrunnsgatan, Uppsala', 
    'Västra Ågatan, Uppsala',
    'Kungsgatan, Uppsala',
    'Svartbäcksgatan, Uppsala',
    'Östra Ågatan, Uppsala',
    'Stora Torget, Uppsala',
    'Fyristorg, Uppsala',
    'Vaksalagatan, Uppsala',
    'Bangårdsgatan, Uppsala',
    'Kungsängsgatan, Uppsala',
    'Studenternas IP, Uppsala',
    'Uppsala Universitet, Uppsala',
    'Centrum, Uppsala',
    'Luthagen, Uppsala',
    'Fålhagen, Uppsala',
    'Eriksberg, Uppsala',
    'Stabby, Uppsala',
    'Sunnersta, Uppsala',
    'Valsätra, Uppsala',
    'Gottsunda, Uppsala',
    'Björkbacken, Uppsala',
    'Librobäck, Uppsala',
    'Gränby, Uppsala',
    'Sävja, Uppsala',
    'Bälinge, Uppsala',
    'Storvreta, Uppsala',
    'Länna, Uppsala',
    'Håbo, Uppsala',
    'Enköping, Uppsala',
    'Östhammar, Uppsala',
    'Tierp, Uppsala',
    'Älvkarleby, Uppsala',
    'Heby, Uppsala',
    'Morgongåva, Uppsala',
    'Skutskär, Uppsala',
    'Sandviken, Uppsala',
    'Hofors, Uppsala',
    'Ockelbo, Uppsala',
    'Ovanåker, Uppsala',
    'Ljusdal, Uppsala',
    'Bollnäs, Uppsala',
    'Söderhamn, Uppsala',
    'Hudiksvall, Uppsala',
    'Nordanstig, Uppsala',
    
    // Linköping
    'Stora Torget, Linköping',
    'Klostergatan, Linköping', 
    'Järnvägsgatan, Linköping',
    'Platensgatan, Linköping',
    'Drottninggatan, Linköping',
    'Kungsgatan, Linköping',
    'Stångågatan, Linköping',
    'Nygatan, Linköping',
    'Hunnebergsgatan, Linköping',
    'Sankt Larsgatan, Linköping',
    'Slottsbacken, Linköping',
    'Centrum, Linköping',
    'Innerstaden, Linköping',
    'Vasastaden, Linköping',
    'Berg, Linköping',
    'Ryd, Linköping',
    'Lambohov, Linköping',
    'Tornby, Linköping',
    'Skäggetorp, Linköping',
    'Berga, Linköping',
    'Hackefors, Linköping',
    'Tannefors, Linköping',
    'Johannelund, Linköping',
    'Vimanshäll, Linköping',
    'Malmslätt, Linköping',
    'Sturefors, Linköping',
    'Vikingstad, Linköping',
    'Motala, Linköping',
    'Vadstena, Linköping',
    'Mjölby, Linköping',
    'Skänninge, Linköping',
    'Åtvidaberg, Linköping',
    'Valdemarsvik, Linköping',
    'Finspång, Linköping',
    'Norrköping, Linköping',
    
    // Örebro
    'Drottninggatan, Örebro',
    'Järnvägsgatan, Örebro',
    'Stortorget, Örebro',
    'Kungsgatan, Örebro',
    'Köpmangatan, Örebro',
    'Fredsgatan, Örebro',
    'Slottsgatan, Örebro',
    'Vasagatan, Örebro',
    'Olof Palmes Gata, Örebro',
    'Nygatan, Örebro',
    'Centrum, Örebro',
    'Norr, Örebro',
    'Söder, Örebro',
    'Vivalla, Örebro',
    'Brickebacken, Örebro',
    'Adolfsberg, Örebro',
    'Marieberg, Örebro',
    'Lundby, Örebro',
    'Almby, Örebro',
    'Varberg, Örebro',
    'Karlslund, Örebro',
    'Mellringe, Örebro',
    'Sörby, Örebro',
    'Tybble, Örebro',
    'Blackeberg, Örebro',
    'Kumla, Örebro',
    'Hallsberg, Örebro',
    'Degerfors, Örebro',
    'Karlskoga, Örebro',
    'Filipstad, Örebro',
    'Hagfors, Örebro',
    'Munkfors, Örebro',
    'Forshaga, Örebro',
    'Grums, Örebro',
    'Årjäng, Örebro',
    'Sunne, Örebro',
    'Torsby, Örebro',
    'Storfors, Örebro',
    'Hammarö, Örebro',
    'Säffle, Örebro',
    'Åmål, Örebro',
    'Bengtsfors, Örebro',
    'Mellerud, Örebro',
    'Dals-Ed, Örebro',
    'Färgelanda, Örebro',
    'Ale, Örebro',
    'Lerum, Örebro',
    'Vårgårda, Örebro',
    'Bollebygd, Örebro',
    'Grästorp, Örebro',
    'Essunga, Örebro',
    'Karlsborg, Örebro',
    'Gullspång, Örebro',
    'Tranemo, Örebro',
    'Bengtsfors, Örebro',
    'Åmål, Örebro',
    'Säffle, Örebro',
    'Kil, Örebro',
    'Eda, Örebro',
    'Skoghall, Örebro',
    'Kristinehamn, Örebro',
    'Storfors, Örebro',
    'Munkfors, Örebro',
    'Hagfors, Örebro',
    'Filipstad, Örebro',
    'Lesjöfors, Örebro',
    'Persberg, Örebro',
    'Nykroppa, Örebro',
    'Degerfors, Örebro',
    'Karlskoga, Örebro',
    'Hällefors, Örebro',
    'Ljusnarsberg, Örebro',
    'Lindesberg, Örebro',
    'Nora, Örebro',
    'Hallsberg, Örebro',
    'Kumla, Örebro',
    'Askersund, Örebro',
    'Laxå, Örebro',
    'Lekeberg, Örebro',
    
    // Västerås
    'Kopparbergsvägen, Västerås',
    'Stora Torget, Västerås',
    'Vasagatan, Västerås',
    'Fiskartorget, Västerås',
    'Sturegatan, Västerås',
    'Kristiansborgsvägen, Västerås',
    'Centrum, Västerås',
    'Malmaberg, Västerås',
    'Hälla, Västerås',
    'Bäckby, Västerås',
    'Råby, Västerås',
    'Vallby, Västerås',
    'Pettersberg, Västerås',
    'Björnö, Västerås',
    'Oxelösund, Västerås',
    'Flen, Västerås',
    'Katrineholm, Västerås',
    'Vingåker, Västerås',
    'Gnesta, Västerås',
    'Nyköping, Västerås',
    'Trosa, Västerås',
    'Vagnhärad, Västerås',
    'Mariefred, Västerås',
    'Strängnäs, Västerås',
    'Eskilstuna, Västerås',
    'Torshälla, Västerås',
    'Sundbyholm, Västerås',
    'Hallstahammar, Västerås',
    'Surahammar, Västerås',
    'Kungsör, Västerås',
    'Köping, Västerås',
    'Arboga, Västerås',
    'Kolsva, Västerås',
    'Ramnäs, Västerås',
    'Virsbo, Västerås',
    'Ängelsberg, Västerås',
    'Norberg, Västerås',
    'Skinnskatteberg, Västerås',
    'Fagersta, Västerås',
    'Sala, Västerås',
    'Avesta, Västerås',
    'Hedemora, Västerås',
    'Säter, Västerås',
    'Sandviken, Västerås',
    'Hofors, Västerås',
    'Ockelbo, Västerås',
    'Ovanåker, Västerås',
    'Ljusdal, Västerås',
    'Bollnäs, Västerås',
    'Söderhamn, Västerås',
    'Hudiksvall, Västerås',
    'Nordanstig, Västerås',
    'Sundsvall, Västerås',
    'Timrå, Västerås',
    'Härnösand, Västerås',
    'Kramfors, Västerås',
    'Sollefteå, Västerås',
    'Örnsköldsvik, Västerås',
    
    // Norrköping
    'Drottninggatan, Norrköping',
    'Holmens Gata, Norrköping',
    'Promenadstråket, Norrköping',
    'Sankt Persgatan, Norrköping',
    'Gamla Rådstugatan, Norrköping',
    'Repslagaregatan, Norrköping',
    'Kristinagatan, Norrköping',
    'Centrum, Norrköping',
    'Innerstaden, Norrköping',
    'Östermalm, Norrköping',
    'Navestad, Norrköping',
    'Hageby, Norrköping',
    'Rinkeby, Norrköping',
    'Vrinnevi, Norrköping',
    'Lindö, Norrköping',
    'Klockaretorpet, Norrköping',
    'Smedby, Norrköping',
    'Åby, Norrköping',
    'Vikbolandet, Norrköping',
    'Kolmården, Norrköping',
    'Braborg, Norrköping',
    'Kimstad, Norrköping',
    'Skärblacka, Norrköping',
    'Oxelösund, Norrköping',
    'Flen, Norrköping',
    'Katrineholm, Norrköping',
    'Vingåker, Norrköping',
    'Gnesta, Norrköping',
    'Nyköping, Norrköping',
    'Trosa, Norrköping',
    'Vagnhärad, Norrköping',
    'Mariefred, Norrköping',
    'Strängnäs, Norrköping',
    'Eskilstuna, Norrköping',
    'Torshälla, Norrköping',
    'Sundbyholm, Norrköping',
    'Hallstahammar, Norrköping',
    'Surahammar, Norrköping',
    'Kungsör, Norrköping',
    'Köping, Norrköping',
    'Arboga, Norrköping',
    'Kolsva, Norrköping',
    'Ramnäs, Norrköping',
    'Virsbo, Norrköping',
    'Ängelsberg, Norrköping',
    'Norberg, Norrköping',
    'Skinnskatteberg, Norrköping',
    'Fagersta, Norrköping',
    'Sala, Norrköping',
    
    // Helsingborg
    'Kullagatan, Helsingborg',
    'Järnvägsgatan, Helsingborg',
    'Stortorget, Helsingborg',
    'Drottninggatan, Helsingborg',
    'Bruksgatan, Helsingborg',
    'Sundstorget, Helsingborg',
    'Centrum, Helsingborg',
    'Söder, Helsingborg',
    'Norr, Helsingborg',
    'Drottninghög, Helsingborg',
    'Fredriksdal, Helsingborg',
    'Rydebäck, Helsingborg',
    'Ramlösa, Helsingborg',
    'Påarp, Helsingborg',
    'Raus, Helsingborg',
    'Örby, Helsingborg',
    'Ödåkra, Helsingborg',
    'Vallåkra, Helsingborg',
    'Väla, Helsingborg',
    'Landskrona, Helsingborg',
    'Svalöv, Helsingborg',
    'Staffanstorp, Helsingborg',
    'Burlöv, Helsingborg',
    'Åstorp, Helsingborg',
    'Bjuv, Helsingborg',
    'Bårslöv, Helsingborg',
    'Billesholm, Helsingborg',
    'Ekeby, Helsingborg',
    'Munka-Ljungby, Helsingborg',
    'Ängelholm, Helsingborg',
    'Båstad, Helsingborg',
    'Höganäs, Helsingborg',
    'Mölle, Helsingborg',
    'Arild, Helsingborg',
    'Torekov, Helsingborg',
    'Klippan, Helsingborg',
    'Perstorp, Helsingborg',
    'Örkelljunga, Helsingborg',
    'Markaryd, Helsingborg',
    'Strömstad, Helsingborg',
    'Tanum, Helsingborg',
    'Sotenäs, Helsingborg',
    'Munkedal, Helsingborg',
    'Orust, Helsingborg',
    'Tjörn, Helsingborg',
    'Stenungsund, Helsingborg',
    'Kungälv, Helsingborg',
    'Ale, Helsingborg',
    'Lerum, Helsingborg',
    'Vårgårda, Helsingborg',
    'Bollebygd, Helsingborg',
    'Grästorp, Helsingborg',
    'Essunga, Helsingborg',
    'Karlsborg, Helsingborg',
    'Gullspång, Helsingborg',
    'Tranemo, Helsingborg',
    'Bengtsfors, Helsingborg',
    'Åmål, Helsingborg',
    'Säffle, Helsingborg',
    'Kil, Helsingborg',
    'Eda, Helsingborg',
    'Skoghall, Helsingborg',
    'Kristinehamn, Helsingborg',
    'Storfors, Helsingborg',
    'Munkfors, Helsingborg',
    'Hagfors, Helsingborg',
    'Filipstad, Helsingborg',
    'Lesjöfors, Helsingborg',
    'Persberg, Helsingborg',
    'Nykroppa, Helsingborg',
    'Degerfors, Helsingborg',
    'Karlskoga, Helsingborg',
    
    // Jönköping
    'Västra Storgatan, Jönköping',
    'Östra Storgatan, Jönköping',
    'Köpmangatan, Jönköping',
    'Klostergatan, Jönköping',
    'Kungsgatan, Jönköping',
    'Barnarpsgatan, Jönköping',
    'Centrum, Jönköping',
    'Östermalm, Jönköping',
    'Väster, Jönköping',
    'Söder, Jönköping',
    'Rosenlund, Jönköping',
    'Råslätt, Jönköping',
    'Huskvarna, Jönköping',
    'Bankeryd, Jönköping',
    'Taberg, Jönköping',
    'Habo, Jönköping',
    'Mullsjö, Jönköping',
    'Vaggeryd, Jönköping',
    'Sävsjö, Jönköping',
    'Vetlanda, Jönköping',
    'Eksjö, Jönköping',
    'Tranås, Jönköping',
    'Ydre, Jönköping',
    'Kinda, Jönköping',
    'Boxholm, Jönköping',
    'Åtvidaberg, Jönköping',
    'Finspång, Jönköping',
    'Valdemarsvik, Jönköping',
    'Linköping, Jönköping',
    'Norrköping, Jönköping',
    'Söderköping, Jönköping',
    'Motala, Jönköping',
    'Vadstena, Jönköping',
    'Mjölby, Jönköping',
    'Aneby, Jönköping',
    'Gnosjö, Jönköping',
    'Värnamo, Jönköping',
    'Ljungby, Jönköping',
    'Växjö, Jönköping',
    'Alvesta, Jönköping',
    'Lessebo, Jönköping',
    'Tingsryd, Jönköping',
    'Uppvidinge, Jönköping',
    'Åseda, Jönköping',
    'Emmaboda, Jönköping',
    'Kalmar, Jönköping',
    'Nybro, Jönköping',
    'Oskarshamn, Jönköping',
    'Västervik, Jönköping',
    'Vimmerby, Jönköping',
    'Hultsfred, Jönköping',
    'Mönsterås, Jönköping',
    'Borgholm, Jönköping',
    'Mörbylånga, Jönköping',
    
    // Lund
    'Stora Södergatan, Lund',
    'Sankt Petri Kyrkogata, Lund',
    'Klostergatan, Lund',
    'Kungsgatan, Lund',
    'Bantorget, Lund',
    'Stortorget, Lund',
    'Mårtenstorget, Lund',
    'Akademiska Föreningen, Lund',
    'Lunds Universitet, Lund',
    'Centrum, Lund',
    'Nöbbelöv, Lund',
    'Vikhem, Lund',
    'Gunnesbo, Lund',
    'Parentuna, Lund',
    'Värpinge, Lund',
    'Dalby, Lund',
    'Genarp, Lund',
    'Veberöd, Lund',
    'Södra Sandby, Lund',
    'Örtofta, Lund',
    'Bjärred, Lund',
    'Lomma, Lund',
    'Alnarp, Lund',
    'Åkarp, Lund',
    'Hjärup, Lund',
    'Staffanstorp, Lund',
    'Eslöv, Lund',
    'Höör, Lund',
    'Hörby, Lund',
    'Sjöbo, Lund',
    'Skurup, Lund',
    'Svedala, Lund',
    'Trelleborg, Lund',
    'Vellinge, Lund',
    'Malmö, Lund',
    'Burlöv, Lund',
    'Kävlinge, Lund',
    'Furulund, Lund',
    'Åkarp, Lund',
    'Bjärred, Lund',
    'Lomma, Lund',
    'Alnarp, Lund',
    'Åkarp, Lund',
    'Hjärup, Lund',
    'Staffanstorp, Lund',
    'Eslöv, Lund',
    'Höör, Lund',
    'Hörby, Lund',
    'Sjöbo, Lund',
    'Skurup, Lund',
    'Svedala, Lund',
    'Trelleborg, Lund',
    'Vellinge, Lund',
    'Malmö, Lund',
    'Burlöv, Lund',
    'Kävlinge, Lund',
    'Furulund, Lund',
    
    // Umeå
    'Storgatan, Umeå',
    'Rådhusesplanaden, Umeå',
    'Västra Esplanaden, Umeå',
    'Östra Esplanaden, Umeå',
    'Kungsgatan, Umeå',
    'Skolgatan, Umeå',
    'Nygatan, Umeå',
    'Renmarkstorget, Umeå',
    'Centrum, Umeå',
    'Västerslätt, Umeå',
    'Ersboda, Umeå',
    'Mariehem, Umeå',
    'Sandbacka, Umeå',
    'Holmsund, Umeå',
    'Obbola, Umeå',
    'Hörnefors, Umeå',
    'Sävar, Umeå',
    'Rödålund, Umeå',
    'Tavleliden, Umeå',
    'Olofsfors, Umeå',
    'Bjurholm, Umeå',
    'Vindeln, Umeå',
    'Robertsfors, Umeå',
    'Nordmaling, Umeå',
    'Örnsköldsvik, Umeå',
    'Kramfors, Umeå',
    'Sollefteå, Umeå',
    'Junsele, Umeå',
    'Ramsele, Umeå',
    'Backe, Umeå',
    'Bispgården, Umeå',
    'Ragunda, Umeå',
    'Hammarstrand, Umeå',
    'Stugun, Umeå',
    'Hoting, Umeå',
    'Strömsund, Umeå',
    'Frostviken, Umeå',
    'Dorotea, Umeå',
    'Vilhelmina, Umeå',
    'Åsele, Umeå',
    'Wilhelmina, Umeå',
    'Storuman, Umeå',
    'Sorsele, Umeå',
    'Malå, Umeå',
    'Norsjö, Umeå',
    'Skellefteå, Umeå',
    'Lycksele, Umeå',
    'Vindeln, Umeå',
    'Robertsfors, Umeå',
    'Vännäs, Umeå',
    'Nordmaling, Umeå',
    'Bjurholm, Umeå',
    
    // Gävle
    'Drottninggatan, Gävle',
    'Nygatan, Gävle',
    'Slottstorget, Gävle',
    'Boulognerskogen, Gävle',
    'Heliga Trefaldighets Kyrka, Gävle',
    'Centrum, Gävle',
    'Norr, Gävle',
    'Söder, Gävle',
    'Brynäs, Gävle',
    'Strömsbro, Gävle',
    'Sätra, Gävle',
    'Andersberg, Gävle',
    'Bomhus, Gävle',
    'Hemlingby, Gävle',
    'Valbo, Gävle',
    'Kungsbäck, Gävle',
    'Skutskär, Gävle',
    'Sandviken, Gävle',
    'Hofors, Gävle',
    'Ockelbo, Gävle',
    'Ovanåker, Gävle',
    'Ljusdal, Gävle',
    'Bollnäs, Gävle',
    'Söderhamn, Gävle',
    'Hudiksvall, Gävle',
    'Nordanstig, Gävle',
    'Sundsvall, Gävle',
    'Timrå, Gävle',
    'Härnösand, Gävle',
    'Kramfors, Gävle',
    'Sollefteå, Gävle',
    'Örnsköldsvik, Gävle',
    'Bjurholm, Gävle',
    'Vindeln, Gävle',
    'Robertsfors, Gävle',
    'Vännäs, Gävle',
    'Umeå, Gävle',
    'Nordmaling, Gävle',
    'Hörnefors, Gävle',
    'Holmsund, Gävle',
    'Obbola, Gävle',
    'Sävar, Gävle',
    'Rödålund, Gävle',
    'Tavleliden, Gävle',
    'Olofsfors, Gävle',
    'Skellefteå, Gävle',
    'Lycksele, Gävle',
    'Storuman, Gävle',
    'Sorsele, Gävle',
    'Malå, Gävle',
    'Norsjö, Gävle',
    'Piteå, Gävle',
    'Älvsbyn, Gävle',
    'Luleå, Gävle',
    'Boden, Gävle',
    'Haparanda, Gävle',
    'Överkalix, Gävle',
    'Kalix, Gävle',
    'Övertorneå, Gävle',
    'Pajala, Gävle',
    'Gällivare, Gävle',
    'Jokkmokk, Gävle',
    'Arjeplog, Gävle',
    'Arvidsjaur, Gävle',
    'Kiruna, Gävle',
    
    // Borås
    'Allégatan, Borås',
    'Stora Torget, Borås',
    'Kungsgatan, Borås',
    'Sandwallsgatan, Borås',
    'Skaraborgsvägen, Borås',
    'Centrum, Borås',
    'Norrby, Borås',
    'Sjöbo, Borås',
    'Hulta, Borås',
    'Trandared, Borås',
    'Dalsjöfors, Borås',
    'Sandhult, Borås',
    'Rydboholm, Borås',
    'Fristad, Borås',
    'Seglora, Borås',
    'Rångedala, Borås',
    'Sandared, Borås',
    'Kinna, Borås',
    'Skene, Borås',
    'Örby, Borås',
    'Länghem, Borås',
    'Svenljunga, Borås',
    'Tranemo, Borås',
    'Jönköping, Borås',
    'Värnamo, Borås',
    'Gislaved, Borås',
    'Vaggeryd, Borås',
    'Gnosjö, Borås',
    'Smålandsstenar, Borås',
    'Hillerstorp, Borås',
    'Reftele, Borås',
    'Markaryd, Borås',
    'Alvesta, Borås',
    'Växjö, Borås',
    'Ljungby, Borås',
    'Lessebo, Borås',
    'Tingsryd, Borås',
    'Uppvidinge, Borås',
    'Åseda, Borås',
    'Emmaboda, Borås',
    'Kalmar, Borås',
    'Nybro, Borås',
    'Oskarshamn, Borås',
    'Västervik, Borås',
    'Vimmerby, Borås',
    'Hultsfred, Borås',
    'Mönsterås, Borås',
    'Borgholm, Borås',
    'Mörbylånga, Borås',
    'Gotland, Borås',
    'Visby, Borås',
    'Roma, Borås',
    'Hemse, Borås',
    'Slite, Borås',
    'Klintehamn, Borås',
    'Burgsvik, Borås',
    'Fårösund, Borås',
    
    // Eskilstuna
    'Drottninggatan, Eskilstuna',
    'Rademachergatan, Eskilstuna',
    'Kriebsensgatan, Eskilstuna',
    'Köpmangatan, Eskilstuna',
    'Faktorigatan, Eskilstuna',
    'Centrum, Eskilstuna',
    'Norr, Eskilstuna',
    'Söder, Eskilstuna',
    'Väster, Eskilstuna',
    'Östermalm, Eskilstuna',
    'Fröslunda, Eskilstuna',
    'Årby, Eskilstuna',
    'Vilsta, Eskilstuna',
    'Lagersberg, Eskilstuna',
    'Torshälla, Eskilstuna',
    'Sundbyholm, Eskilstuna',
    'Hallstahammar, Eskilstuna',
    'Surahammar, Eskilstuna',
    'Kungsör, Eskilstuna',
    'Köping, Eskilstuna',
    'Arboga, Eskilstuna',
    'Kolsva, Eskilstuna',
    'Ramnäs, Eskilstuna',
    'Virsbo, Eskilstuna',
    'Ängelsberg, Eskilstuna',
    'Norberg, Eskilstuna',
    'Skinnskatteberg, Eskilstuna',
    'Fagersta, Eskilstuna',
    'Sala, Eskilstuna',
    'Avesta, Eskilstuna',
    'Hedemora, Eskilstuna',
    'Säter, Eskilstuna',
    'Sandviken, Eskilstuna',
    'Hofors, Eskilstuna',
    'Ockelbo, Eskilstuna',
    'Ovanåker, Eskilstuna',
    'Ljusdal, Eskilstuna',
    'Bollnäs, Eskilstuna',
    'Söderhamn, Eskilstuna',
    'Hudiksvall, Eskilstuna',
    'Nordanstig, Eskilstuna',
    'Sundsvall, Eskilstuna',
    'Timrå, Eskilstuna',
    'Härnösand, Eskilstuna',
    'Kramfors, Eskilstuna',
    'Sollefteå, Eskilstuna',
    'Örnsköldsvik, Eskilstuna',
    'Bjurholm, Eskilstuna',
    'Vindeln, Eskilstuna',
    'Robertsfors, Eskilstuna',
    'Vännäs, Eskilstuna',
    'Umeå, Eskilstuna',
    'Nordmaling, Eskilstuna',
    'Hörnefors, Eskilstuna',
    'Holmsund, Eskilstuna',
    'Obbola, Eskilstuna',
    'Sävar, Eskilstuna',
    'Rödålund, Eskilstuna',
    'Tavleliden, Eskilstuna',
    'Olofsfors, Eskilstuna',
    'Skellefteå, Eskilstuna',
    'Lycksele, Eskilstuna',
    'Storuman, Eskilstuna',
    'Sorsele, Eskilstuna',
    'Malå, Eskilstuna',
    'Norsjö, Eskilstuna',
    'Piteå, Eskilstuna',
    'Älvsbyn, Eskilstuna',
    'Luleå, Eskilstuna',
    'Boden, Eskilstuna',
    'Haparanda, Eskilstuna',
    'Överkalix, Eskilstuna',
    'Kalix, Eskilstuna',
    'Övertorneå, Eskilstuna',
    'Pajala, Eskilstuna',
    'Gällivare, Eskilstuna',
    'Jokkmokk, Eskilstuna',
    'Arjeplog, Eskilstuna',
    'Arvidsjaur, Eskilstuna',
    'Kiruna, Eskilstuna',
    
    // Karlstad
    'Västra Torggatan, Karlstad',
    'Tingvallagatan, Karlstad',
    'Drottninggatan, Karlstad',
    'Köpmangatan, Karlstad',
    'Järnvägsgatan, Karlstad',
    'Stora Torget, Karlstad',
    'Centrum, Karlstad',
    'Kronoparken, Karlstad',
    'Våxnäs, Karlstad',
    'Bellevue, Karlstad',
    'Herrhagen, Karlstad',
    'Rud, Karlstad',
    'Sundsta, Karlstad',
    'Skårby, Karlstad',
    'Sandgrund, Karlstad',
    'Löfbergs Lila Arena, Karlstad',
    'Mariebergsskogen, Karlstad',
    'Hammarö, Karlstad',
    'Skoghall, Karlstad',
    'Grums, Karlstad',
    'Munkfors, Karlstad',
    'Forshaga, Karlstad',
    'Kil, Karlstad',
    'Sunne, Karlstad',
    'Torsby, Karlstad',
    'Hagfors, Karlstad',
    'Filipstad, Karlstad',
    'Storfors, Karlstad',
    'Årjäng, Karlstad',
    'Eda, Karlstad',
    'Säffle, Karlstad',
    'Åmål, Karlstad',
    'Bengtsfors, Karlstad',
    'Mellerud, Karlstad',
    'Dals-Ed, Karlstad',
    'Färgelanda, Karlstad',
    'Ale, Karlstad',
    'Lerum, Karlstad',
    'Vårgårda, Karlstad',
    'Bollebygd, Karlstad',
    'Grästorp, Karlstad',
    'Essunga, Karlstad',
    'Karlsborg, Karlstad',
    'Gullspång, Karlstad',
    'Tranemo, Karlstad',
    'Bengtsfors, Karlstad',
    'Åmål, Karlstad',
    'Säffle, Karlstad',
    'Kil, Karlstad',
    'Eda, Karlstad',
    'Skoghall, Karlstad',
    'Kristinehamn, Karlstad',
    'Storfors, Karlstad',
    'Munkfors, Karlstad',
    'Hagfors, Karlstad',
    'Filipstad, Karlstad',
    'Lesjöfors, Karlstad',
    'Persberg, Karlstad',
    'Nykroppa, Karlstad',
    'Degerfors, Karlstad',
    'Karlskoga, Karlstad',
    'Hällefors, Karlstad',
    'Ljusnarsberg, Karlstad',
    'Lindesberg, Karlstad',
    'Nora, Karlstad',
    'Hallsberg, Karlstad',
    'Kumla, Karlstad',
    'Askersund, Karlstad',
    'Laxå, Karlstad',
    'Lekeberg, Karlstad',
    'Örebro, Karlstad',
    
    // Vanliga gatunamn som förekommer i många svenska städer
    'Storgatan',
    'Järnvägsgatan', 
    'Kungsgatan',
    'Drottninggatan',
    'Stora Torget',
    'Köpmangatan',
    'Skolgatan',
    'Kyrkogatan',
    'Nygatan',
    'Stationsgatan',
    'Parkgatan',
    'Rådhusgatan',
    'Hamngatan',
    'Brogatan',
    'Slottsgatan',
    'Teatergatan',
    'Biblioteksgatan',
    'Sjukhussgatan',
    'Hospitalsgatan',
    'Apoteksgatan',
    'Postgatan',
    'Telegrafgatan',
    'Banérgatan',
    'Industrigatn',
    'Fabriksgatan',
    'Handelsgatan',
    'Marknadsgatan',
    'Torggatan',
    'Salutorget',
    'Fisktorget',
    'Hötorget',
    'Östergatan',
    'Västergatan',
    'Södergatan',
    'Norra gatan',
    'Södra gatan'
  ];

  // Sök efter matchande gatunamn
  REAL_SWEDISH_ADDRESSES.forEach(address => {
    if (address.toLowerCase().includes(searchTerm)) {
      suggestions.push(address);
    }
  });

  // Lägg till gatunamn med husnummer för mer realistiska förslag
  if (searchTerm.length >= 3) {
    const matchingStreets = suggestions.slice(0, 3);
    const commonNumbers = ['1', '2', '3', '5', '10', '12', '15', '20'];
    
    matchingStreets.forEach(street => {
      commonNumbers.slice(0, 2).forEach(num => {
        const [streetName, city] = street.split(', ');
        suggestions.push(`${streetName} ${num}, ${city}`);
      });
    });
  }

  return suggestions.slice(0, 8);
}

/**
 * Parse an address string into components
 */
export const parseAddress = (address: string): AddressResult | null => {
  try {
    const parts = address.split(', ');
    
    if (parts.length >= 2) {
      const streetPart = parts[0].trim();
      const locationPart = parts[1].trim();
      
      // Extrahera husnummer om det finns
      const streetMatch = streetPart.match(/^(.+?)(\s+\d+.*)?$/);
      const street = streetMatch ? streetMatch[1].trim() : streetPart;
      const number = streetMatch && streetMatch[2] ? streetMatch[2].trim() : undefined;
      
      // Hantera postnummer i locationPart
      const postalMatch = locationPart.match(/^(.+?)\s+(\d{3}\s?\d{2})$/);
      const city = postalMatch ? postalMatch[1].trim() : locationPart;
      const postalCode = postalMatch ? postalMatch[2].replace(/\s/g, '') : '';
      
      return {
        street,
        number,
        postalCode,
        city,
        fullAddress: address
      };
    }
    
    return null;
  } catch (error) {
    console.error('Error parsing address:', error);
    return null;
  }
};

/**
 * Format address for display
 */
export const formatAddress = (address: string | AddressResult): string => {
  if (typeof address === 'string') {
    return address;
  }
  
  let formatted = address.street;
  if (address.number) {
    formatted += ` ${address.number}`;
  }
  if (address.city) {
    formatted += `, ${address.city}`;
  }
  if (address.postalCode) {
    formatted += ` ${address.postalCode.substring(0, 3)} ${address.postalCode.substring(3)}`;
  }
  
  return formatted;
};