export const SWEDISH_INDUSTRIES = [
  // Bemanning och personaluthyrning
  'Bemanningsbranschen',
  'Personaluthyrning',
  'Rekrytering och headhunting',
  'HR-tjänster',
  'Temp-anställningar',
  'Konsultförmedling',
  
  // Primära sektorer
  'Jordbruk och trädgård',
  'Skogsbruk',
  'Fiske och vattenbruk',
  'Gruvdrift och utvinning',
  
  // Sekundära sektorer - Tillverkning och industri
  'Livsmedelsproduktion',
  'Dryckesproduktion',
  'Textil och beklädnad',
  'Trä- och möbelindustri',
  'Papper och förpackning',
  'Kemisk industri',
  'Läkemedel och bioteknik',
  'Plast och gummi',
  'Glas, keramik och cement',
  'Metall och metallbearbetning',
  'Maskintillverkning',
  'Fordonsindustri',
  'Elektronik och halvledare',
  'Optisk och medicinteknisk utrustning',
  'Möbler och inredning',
  'Återvinning och avfallshantering',
  
  // Energi och utilities
  'Elproduktion och distribution',
  'Gasförsörjning',
  'Vattenförsörjning',
  'Avloppsrening',
  'Fjärrvärme och kyla',
  'Förnybar energi',
  'Kärnkraft',
  'Olja och petroleum',
  
  // Bygg och anläggning
  'Husbyggnad',
  'Anläggningsbyggnad',
  'Specialbyggnad',
  'Rivning och sanering',
  'Elinstallation',
  'VVS-installation',
  'Måleri och puts',
  'Golv och kakel',
  'Byggmaterial handel',
  
  // Transport och logistik
  'Lastbilstransport',
  'Järnvägstransport',
  'Sjöfart och hamnar',
  'Flygtransport och flygplatser',
  'Kollektivtrafik',
  'Taxi och biltjänster',
  'Kurirtjänster och post',
  'Magasinering och lager',
  'Spedition och frakt',
  'Rörledningar',
  
  // Handel
  'Grosshandel',
  'Dagligvaruhandel',
  'Kläder och skor',
  'Heminredning och möbler',
  'Elektronik och vitvaror',
  'Bygg och trädgård handel',
  'Fordon och reservdelar',
  'Drivmedel och bensinstationer',
  'Apotek och hälsokost',
  'Bokhandel och papper',
  'Sport och fritid handel',
  'Leksaker och spel',
  'Blommor och trädgård',
  'Djur och djurtillbehör',
  'Second hand och antikviteter',
  
  // Hotell, restaurang och turism
  'Hotell och logi',
  'Restauranger och catering',
  'Barer och pubar',
  'Kafé och konditori',
  'Snabbmat och gatukök',
  'Konferens och event',
  'Nöjesparker och attraktioner',
  'Camping och stugor',
  'Resebyråer och guider',
  'Kryssningar och båtturer',
  
  // Information och kommunikation
  'Mjukvaruutveckling',
  'IT-konsulting',
  'Webbutveckling',
  'Apputveckling',
  'Systemintegration',
  'Databaser och servrar',
  'Cybersäkerhet',
  'Telekommunikation',
  'Internetleverantörer',
  'Medieproduktion',
  'TV och radio',
  'Tidningar och förlag',
  'Grafisk design',
  'Reklam och marknadsföring',
  'Digital marknadsföring',
  'PR och kommunikation',
  'Översättning och tolkning',
  
  // Finans och försäkring
  'Banker',
  'Kreditinstitut',
  'Försäkringsbolag',
  'Pensionsfonder',
  'Investmentbolag',
  'Fastighetsfonder',
  'Mäkleri och värdepapper',
  'Ekonomisk rådgivning',
  'Redovisning och bokföring',
  'Revision',
  'Skatterådgivning',
  'Factoring och leasing',
  
  // Fastigheter
  'Fastighetsutveckling',
  'Fastighetsförvaltning',
  'Fastighetsmäkleri',
  'Fastighetstaxering',
  'Facility management',
  'Städ och renhållning',
  'Säkerhet och bevakning',
  'Trädgårdsskötsel och park',
  'Snöröjning och vinterservice',
  
  // Professionella tjänster
  'Juridik och advokatbyråer',
  'Managementkonsulting',
  'Teknisk konsulting',
  'HR-konsulting',
  'Miljökonsulting',
  'Arkitektur och design',
  'Ingenjörstjänster',
  'Forskning och utveckling',
  'Laboratoriverksamhet',
  'Marknadsanalys',
  'Projektledning',
  
  // Offentlig sektor
  'Statlig förvaltning',
  'Kommunal förvaltning',
  'Regionförvaltning',
  'Försvar och militär',
  'Polis och rättsväsen',
  'Brandkår och räddningstjänst',
  'Skattemyndighet',
  'Arbetsförmedling',
  'Försäkringskassan',
  'Pensionsmyndighet',
  'Tullverket',
  'Migrationsverket',
  
  // Utbildning
  'Förskola',
  'Grundskola',
  'Gymnasium',
  'Yrkeshögskola',
  'Universitet och högskola',
  'Komvux och vuxenutbildning',
  'Språkskolor',
  'Körskolor',
  'Musikskolor',
  'Konstskolor',
  'Idrottsskolor',
  'Företagsutbildning',
  'E-learning och distansutbildning',
  
  // Hälso- och sjukvård
  'Sjukhus',
  'Vårdcentraler',
  'Specialistmottagningar',
  'Tandvård',
  'Veterinärvård',
  'Apotek',
  'Hemsjukvård',
  'Äldreomsorg',
  'Funktionshinderomsorg',
  'Psykiatri och psykologi',
  'Fysioterapi och sjukgymnastik',
  'Arbetsterapi',
  'Dietist och näring',
  'Alternativ medicin',
  'Medicinsk forskning',
  
  // Sociala tjänster
  'Barnomsorg och förskola',
  'Äldreomsorg',
  'Handikappomsorg',
  'Socialtjänst',
  'Familjerådgivning',
  'Missbruksvård',
  'Hemlöshetsstöd',
  'Flyktingmottagning',
  'Volontärorganisationer',
  'Stiftelser och ideell sektor',
  
  // Kultur, sport och underhållning  
  'Teater och scen',
  'Musik och konsert',
  'Film och TV-produktion',
  'Museer och gallerier',
  'Bibliotek',
  'Sportklubbar och gym',
  'Idrottsanläggningar',
  'Spa och wellness',
  'Nöjesparker',
  'Kasinon och spel',
  'Festivaler och event',
  'Bokförlag',
  'Konsthantverk',
  
  // Personliga tjänster
  'Frisörsalonger',
  'Skönhetssalonger',
  'Nagelstudios',
  'Massage och terapi',
  'Tvättservice och kemtvätt',
  'Begravningsbyråer',
  'Fotostudios',
  'Bröllopsarrangörer',
  'Personlig träning',
  'Barnpassning',
  'Hushållstjänster',
  'Hundpensionat och hunddagis',
  'Reparationer och service',
  
  // Jordbruk och naturresurser (utökat)
  'Mjölkproduktion',
  'Köttproduktion',
  'Äggproduktion',
  'Spannmålsodling',
  'Grönsaksodling',
  'Fruktodling',
  'Bärodling',
  'Blomsterodling',
  'Växthusodling',
  'Ekologisk odling',
  'Biodling',
  'Pälsdjursuppfödning',
  'Hästhållning och ridskolor',
  
  // Övrigt
  'Medlemsorganisationer',
  'Fackföreningar',
  'Branschorganisationer',
  'Politiska partier',
  'Religiösa organisationer',
  'Internationella organisationer',
  'Konsumentkooperativ',
  'Bostadsrättsföreningar',
  'Samfälligheter',
  'Annat'
];

export const EMPLOYEE_COUNT_OPTIONS = [
  '1-10 anställda',
  '11-50 anställda',
  '51-200 anställda',
  '201-500 anställda',
  '500+ anställda'
];