export const SWEDISH_INDUSTRIES = [
  'Alternativ medicin',
  'Anläggningsbyggnad',
  'Annat',
  'Apotek',
  'Apotek och hälsokost',
  'Apputveckling',
  'Arbetsförmedling',
  'Arbetsterapi',
  'Arkitektur och design',
  'Avloppsrening',
  'Banker',
  'Barer och pubar',
  'Barnomsorg och förskola',
  'Barnpassning',
  'Begravningsbyråer',
  'Bemanningsbranschen',
  'Biodling',
  'Bibliotek',
  'Blommor och trädgård',
  'Blomsterodling',
  'Bokförlag',
  'Bokhandel och papper',
  'Bostadsrättsföreningar',
  'Brandkår och räddningstjänst',
  'Branschorganisationer',
  'Bröllopsarrangörer',
  'Bygg och trädgård handel',
  'Byggmaterial handel',
  'Bärodling',
  'Camping och stugor',
  'Cybersäkerhet',
  'Dagligvaruhandel',
  'Databaser och servrar',
  'Dietist och näring',
  'Digital marknadsföring',
  'Djur och djurtillbehör',
  'Drivmedel och bensinstationer',
  'Dryckesproduktion',
  'E-learning och distansutbildning',
  'Ekonomisk rådgivning',
  'Ekologisk odling',
  'Elektronik och halvledare',
  'Elektronik och vitvaror',
  'Elinstallation',
  'Elproduktion och distribution',
  'Factoring och leasing',
  'Facility management',
  'Fackföreningar',
  'Familjerådgivning',
  'Fastighetsfonder',
  'Fastighetsmäkleri',
  'Fastighetstaxering',
  'Fastighetsutveckling',
  'Fastighetsförvaltning',
  'Festivaler och event',
  'Film och TV-produktion',
  'Fiske och vattenbruk',
  'Fjärrvärme och kyla',
  'Flygtransport och flygplatser',
  'Flyktingmottagning',
  'Fordon och reservdelar',
  'Fordonsindustri',
  'Forskning och utveckling',
  'Fotostudios',
  'Frisörsalonger',
  'Fruktodling',
  'Funktionshinderomsorg',
  'Fysioterapi och sjukgymnastik',
  'Försäljning',
  'Företagsutbildning',
  'Förnybar energi',
  'Förskola',
  'Försäkringsbolag',
  'Försäkringskassan',
  'Försvar och militär',
  'Gasförsörjning',
  'Glas, keramik och cement',
  'Golv och kakel',
  'Grafisk design',
  'Grosshandel',
  'Grundskola',
  'Gruvdrift och utvinning',
  'Grönsaksodling',
  'Gymnasium',
  'Handikappomsorg',
  'Heminredning och möbler',
  'Hemsjukvård',
  'Hemlöshetsstöd',
  'Hotell och logi',
  'HR-konsulting',
  'HR-tjänster',
  'Hundpensionat och hunddagis',
  'Husbyggnad',
  'Hushållstjänster',
  'Hästhållning och ridskolor',
  'Idrottsanläggningar',
  'Idrottsskolor',
  'Ingenjörstjänster',
  'Internationella organisationer',
  'Internetleverantörer',
  'Investmentbolag',
  'IT-konsulting',
  'Jordbruk och trädgård',
  'Juridik och advokatbyråer',
  'Järnvägstransport',
  'Kafé och konditori',
  'Kasinon och spel',
  'Kemisk industri',
  'Kläder och skor',
  'Kollektivtrafik',
  'Kommunal förvaltning',
  'Komvux och vuxenutbildning',
  'Konferens och event',
  'Konsultförmedling',
  'Konsumentkooperativ',
  'Konsthantverk',
  'Konstskolor',
  'Kreditinstitut',
  'Kryssningar och båtturer',
  'Kurirtjänster och post',
  'Körskolor',
  'Köttproduktion',
  'Kärnkraft',
  'Laboratoriverksamhet',
  'Lastbilstransport',
  'Leksaker och spel',
  'Livsmedelsproduktion',
  'Läkemedel och bioteknik',
  'Magasinering och lager',
  'Managementkonsulting',
  'Marknadsanalys',
  'Maskintillverkning',
  'Massage och terapi',
  'Medicinsk forskning',
  'Medieproduktion',
  'Medlemsorganisationer',
  'Metall och metallbearbetning',
  'Migrationsverket',
  'Miljökonsulting',
  'Missbruksvård',
  'Mjukvaruutveckling',
  'Mjölkproduktion',
  'Musik och konsert',
  'Musikskolor',
  'Museer och gallerier',
  'Mäkleri och värdepapper',
  'Måleri och puts',
  'Möbler och inredning',
  'Nagelstudios',
  'Nöjesparker',
  'Nöjesparker och attraktioner',
  'Olja och petroleum',
  'Optisk och medicinteknisk utrustning',
  'Papper och förpackning',
  'Pensionsfonder',
  'Pensionsmyndighet',
  'Personaluthyrning',
  'Personlig träning',
  'Plast och gummi',
  'Polis och rättsväsen',
  'Politiska partier',
  'PR och kommunikation',
  'Projektledning',
  'Psykiatri och psykologi',
  'Pälsdjursuppfödning',
  'Redovisning och bokföring',
  'Regionförvaltning',
  'Rekrytering och headhunting',
  'Reklam och marknadsföring',
  'Religiösa organisationer',
  'Reparationer och service',
  'Resebyråer och guider',
  'Restauranger och catering',
  'Revision',
  'Rivning och sanering',
  'Rörledningar',
  'Samfälligheter',
  'Second hand och antikviteter',
  'Sjukhus',
  'Sjöfart och hamnar',
  'Skattemyndighet',
  'Skatterådgivning',
  'Skogsbruk',
  'Skönhetssalonger',
  'Snabbmat och gatukök',
  'Snöröjning och vinterservice',
  'Socialtjänst',
  'Spa och wellness',
  'Spannmålsodling',
  'Specialbyggnad',
  'Specialistmottagningar',
  'Spedition och frakt',
  'Sport och fritid handel',
  'Sportklubbar och gym',
  'Språkskolor',
  'Statlig förvaltning',
  'Stiftelser och ideell sektor',
  'Städ och renhållning',
  'Systemintegration',
  'Säkerhet och bevakning',
  'Tandvård',
  'Taxi och biltjänster',
  'Teater och scen',
  'Teknisk konsulting',
  'Telekommunikation',
  'Temp-anställningar',
  'Textil och beklädnad',
  'Tidningar och förlag',
  'Trä- och möbelindustri',
  'Trädgårdsskötsel och park',
  'Tullverket',
  'TV och radio',
  'Tvättservice och kemtvätt',
  'Universitet och högskola',
  'Vattenförsörjning',
  'Veterinärvård',
  'VVS-installation',
  'Volontärorganisationer',
  'Vårdcentraler',
  'Växthusodling',
  'Webbutveckling',
  'Yrkeshögskola',
  'Återvinning och avfallshantering',
  'Äldreomsorg',
  'Översättning och tolkning',
  'Äggproduktion'
];

export const EMPLOYEE_COUNT_OPTIONS = [
  '1-10 anställda',
  '11-50 anställda',
  '51-200 anställda',
  '201-500 anställda',
  '500+ anställda'
];
/**
 * Sökalias för branscher: extra ord som också hittar branschen i sökbara
 * dropdowns (registrering, välkomstguide, företagsprofil).
 */
export const INDUSTRY_ALIASES: Record<string, string[]> = {
  'Mjukvaruutveckling': ['IT', 'tech', 'programmering', 'utvecklare', 'software', 'SaaS', 'data'],
  'IT-konsulting': ['IT', 'tech', 'konsult', 'data', 'digitalisering'],
  'Webbutveckling': ['IT', 'tech', 'webb', 'hemsidor', 'frontend', 'programmering'],
  'Apputveckling': ['IT', 'tech', 'appar', 'mobil', 'programmering'],
  'Systemintegration': ['IT', 'tech', 'integration', 'data'],
  'Databaser och servrar': ['IT', 'tech', 'drift', 'hosting', 'moln', 'cloud', 'data'],
  'Cybersäkerhet': ['IT', 'tech', 'säkerhet', 'infosäk', 'security'],
  'Telekommunikation': ['IT', 'telekom', 'mobil', 'tele'],
  'Internetleverantörer': ['IT', 'bredband', 'fiber', 'ISP'],
  'E-learning och distansutbildning': ['utbildning', 'edtech', 'onlinekurser'],
  'Husbyggnad': ['bygg', 'byggföretag', 'snickare', 'entreprenad', 'hantverkare'],
  'Anläggningsbyggnad': ['bygg', 'mark', 'väg', 'infrastruktur', 'entreprenad'],
  'Specialbyggnad': ['bygg', 'entreprenad'],
  'Rivning och sanering': ['bygg', 'asbest', 'demolering'],
  'Måleri och puts': ['bygg', 'målare', 'hantverkare'],
  'Golv och kakel': ['bygg', 'plattsättare', 'golvläggare', 'hantverkare'],
  'Elinstallation': ['bygg', 'elektriker', 'el', 'hantverkare'],
  'VVS-installation': ['bygg', 'rörmokare', 'rör', 'värme', 'hantverkare'],
  'Sjukhus': ['vård', 'sjukvård', 'hälsa', 'region', 'sjuksköterska', 'läkare'],
  'Vårdcentraler': ['vård', 'sjukvård', 'hälsa', 'primärvård', 'läkare'],
  'Hemsjukvård': ['vård', 'sjukvård', 'hemtjänst'],
  'Äldreomsorg': ['vård', 'omsorg', 'hemtjänst', 'äldreboende', 'undersköterska'],
  'Funktionshinderomsorg': ['vård', 'omsorg', 'LSS', 'assistans', 'personlig assistent'],
  'Handikappomsorg': ['vård', 'omsorg', 'LSS', 'assistans', 'personlig assistent'],
  'Specialistmottagningar': ['vård', 'klinik', 'läkare'],
  'Psykiatri och psykologi': ['vård', 'psykolog', 'terapi', 'mental hälsa'],
  'Tandvård': ['vård', 'tandläkare', 'klinik'],
  'Fysioterapi och sjukgymnastik': ['vård', 'fysio', 'rehab'],
  'Veterinärvård': ['djur', 'djursjukhus', 'veterinär'],
  'Läkemedel och bioteknik': ['pharma', 'life science', 'biotech', 'medicin'],
  'Restauranger och catering': ['restaurang', 'mat', 'krog', 'kock', 'hotell och restaurang', 'besöksnäring'],
  'Snabbmat och gatukök': ['restaurang', 'mat', 'fastfood', 'pizzeria'],
  'Kafé och konditori': ['café', 'fik', 'bageri', 'mat'],
  'Barer och pubar': ['restaurang', 'nattklubb', 'krog'],
  'Hotell och logi': ['hotell', 'turism', 'besöksnäring', 'hostel'],
  'Dagligvaruhandel': ['handel', 'butik', 'livsmedelsbutik', 'mataffär', 'retail', 'ICA', 'Coop'],
  'Kläder och skor': ['handel', 'butik', 'mode', 'retail'],
  'Elektronik och vitvaror': ['handel', 'butik', 'retail'],
  'Grosshandel': ['handel', 'partihandel', 'B2B'],
  'Försäljning': ['sälj', 'säljare', 'handel', 'butik'],
  'Banker': ['bank', 'finans', 'ekonomi'],
  'Investmentbolag': ['finans', 'investering', 'private equity', 'riskkapital'],
  'Mäkleri och värdepapper': ['finans', 'aktier', 'börs'],
  'Försäkringsbolag': ['finans', 'försäkring'],
  'Redovisning och bokföring': ['ekonomi', 'redovisningsbyrå', 'bokföringsbyrå', 'lön'],
  'Revision': ['ekonomi', 'revisor', 'redovisning'],
  'Ekonomisk rådgivning': ['ekonomi', 'finans', 'rådgivning'],
  'Juridik och advokatbyråer': ['jurist', 'advokat', 'lag', 'juridisk'],
  'Rekrytering och headhunting': ['HR', 'rekrytering', 'bemanning'],
  'Bemanningsbranschen': ['HR', 'bemanning', 'rekrytering', 'uthyrning'],
  'Personaluthyrning': ['HR', 'bemanning', 'uthyrning'],
  'HR-tjänster': ['HR', 'personal', 'lön'],
  'Reklam och marknadsföring': ['marknad', 'reklambyrå', 'byrå', 'marketing', 'kommunikation'],
  'Digital marknadsföring': ['marknad', 'marketing', 'SEO', 'sociala medier', 'byrå'],
  'PR och kommunikation': ['marknad', 'kommunikation', 'PR-byrå'],
  'Lastbilstransport': ['transport', 'logistik', 'åkeri', 'chaufför'],
  'Spedition och frakt': ['transport', 'logistik', 'frakt'],
  'Magasinering och lager': ['logistik', 'lager', 'truck'],
  'Kurirtjänster och post': ['transport', 'logistik', 'bud', 'leverans'],
  'Taxi och biltjänster': ['transport', 'taxi', 'chaufför'],
  'Kollektivtrafik': ['transport', 'buss', 'tåg', 'lokaltrafik'],
  'Fordonsindustri': ['industri', 'bil', 'tillverkning'],
  'Maskintillverkning': ['industri', 'tillverkning', 'verkstad'],
  'Metall och metallbearbetning': ['industri', 'verkstad', 'svets', 'tillverkning'],
  'Livsmedelsproduktion': ['industri', 'mat', 'tillverkning'],
  'Förnybar energi': ['energi', 'sol', 'vind', 'solceller', 'grön'],
  'Elproduktion och distribution': ['energi', 'el', 'kraft'],
  'Grundskola': ['skola', 'utbildning', 'lärare'],
  'Gymnasium': ['skola', 'utbildning', 'lärare'],
  'Förskola': ['skola', 'barn', 'förskollärare', 'dagis'],
  'Barnomsorg och förskola': ['skola', 'barn', 'förskollärare', 'dagis'],
  'Universitet och högskola': ['skola', 'utbildning', 'akademi', 'forskning'],
  'Kommunal förvaltning': ['kommun', 'offentlig sektor', 'myndighet'],
  'Regionförvaltning': ['region', 'offentlig sektor', 'landsting'],
  'Statlig förvaltning': ['stat', 'offentlig sektor', 'myndighet'],
  'Stiftelser och ideell sektor': ['ideell', 'förening', 'NGO', 'välgörenhet'],
  'Städ och renhållning': ['städning', 'städfirma', 'lokalvård', 'service'],
  'Säkerhet och bevakning': ['väktare', 'bevakning', 'security', 'ordningsvakt'],
  'Frisörsalonger': ['frisör', 'skönhet', 'hår'],
  'Skönhetssalonger': ['skönhet', 'beauty', 'hudvård'],
  'Sportklubbar och gym': ['gym', 'träning', 'fitness', 'sport'],
  'Fastighetsförvaltning': ['fastighet', 'hyresvärd', 'fastighetsbolag'],
  'Fastighetsmäkleri': ['fastighet', 'mäklare', 'bostad'],
  'Film och TV-produktion': ['media', 'film', 'produktion'],
  'Medieproduktion': ['media', 'content', 'produktion'],
  'Alternativ medicin': ['naprapat', 'kiropraktor', 'akupunktur', 'homeopati'],
  'Apotek': ['farmaceut', 'receptarie', 'vård'],
  'Arbetsterapi': ['vård', 'rehab', 'arbetsterapeut'],
  'Arkitektur och design': ['arkitekt', 'inredningsarkitekt', 'design'],
  'Begravningsbyråer': ['begravning', 'jordfästning'],
  'Bibliotek': ['bibliotekarie', 'kultur'],
  'Brandkår och räddningstjänst': ['brandman', 'räddning', 'brand'],
  'Bröllopsarrangörer': ['bröllop', 'event'],
  'Camping och stugor': ['camping', 'turism', 'stuguthyrning'],
  'Dietist och näring': ['kost', 'näringslära', 'vård'],
  'Djur och djurtillbehör': ['djuraffär', 'zoo', 'husdjur'],
  'Drivmedel och bensinstationer': ['mack', 'bensin', 'laddstation'],
  'Elektronik och halvledare': ['industri', 'elektronik', 'chip'],
  'Facility management': ['fastighetsservice', 'service', 'drift'],
  'Fackföreningar': ['facket', 'fack', 'förbund'],
  'Fastighetsutveckling': ['fastighet', 'exploatering', 'bostadsutveckling'],
  'Festivaler och event': ['event', 'evenemang', 'konsert'],
  'Fiske och vattenbruk': ['fisk', 'odling', 'jordbruk'],
  'Flygtransport och flygplatser': ['flyg', 'pilot', 'kabinpersonal', 'flygplats'],
  'Försvar och militär': ['militär', 'försvarsmakten', 'soldat'],
  'Fotostudios': ['fotograf', 'foto'],
  'Grafisk design': ['design', 'formgivning', 'byrå'],
  'Gruvdrift och utvinning': ['gruva', 'industri', 'mineral'],
  'Heminredning och möbler': ['inredning', 'möbler', 'handel', 'butik'],
  'Hushållstjänster': ['RUT', 'städning', 'hemservice'],
  'Hästhållning och ridskolor': ['häst', 'ridning', 'stall'],
  'Ingenjörstjänster': ['ingenjör', 'konsult', 'teknik'],
  'Järnvägstransport': ['tåg', 'järnväg', 'transport'],
  'Jordbruk och trädgård': ['lantbruk', 'bonde', 'jordbruk'],
  'Kemisk industri': ['kemi', 'industri', 'process'],
  'Komvux och vuxenutbildning': ['skola', 'utbildning', 'vuxenutbildning'],
  'Konferens och event': ['event', 'konferens', 'möten'],
  'Körskolor': ['trafikskola', 'körkort', 'trafiklärare'],
  'Laboratoriverksamhet': ['labb', 'lab', 'analys'],
  'Managementkonsulting': ['konsult', 'strategi', 'management'],
  'Massage och terapi': ['massör', 'massage', 'friskvård'],
  'Medicinsk forskning': ['forskning', 'life science', 'klinisk'],
  'Miljökonsulting': ['miljö', 'hållbarhet', 'konsult'],
  'Missbruksvård': ['vård', 'beroende', 'behandlingshem'],
  'Musik och konsert': ['musik', 'konsert', 'kultur'],
  'Museer och gallerier': ['museum', 'galleri', 'kultur'],
  'Nagelstudios': ['naglar', 'skönhet'],
  'Personlig träning': ['PT', 'träning', 'gym', 'fitness'],
  'Polis och rättsväsen': ['polis', 'domstol', 'kriminalvård', 'myndighet'],
  'Projektledning': ['projekt', 'konsult'],
  'Resebyråer och guider': ['resor', 'turism', 'guide'],
  'Reparationer och service': ['reparation', 'service', 'verkstad'],
  'Second hand och antikviteter': ['begagnat', 'antik', 'loppis', 'handel'],
  'Sjöfart och hamnar': ['sjöfart', 'hamn', 'rederi', 'båt'],
  'Skogsbruk': ['skog', 'sågverk', 'jordbruk'],
  'Socialtjänst': ['socionom', 'kommun', 'socialsekreterare'],
  'Spa och wellness': ['spa', 'wellness', 'friskvård'],
  'Språkskolor': ['språk', 'SFI', 'utbildning'],
  'Teater och scen': ['teater', 'scen', 'kultur'],
  'Teknisk konsulting': ['konsult', 'ingenjör', 'teknik'],
  'Textil och beklädnad': ['textil', 'mode', 'kläder'],
  'Tidningar och förlag': ['media', 'journalistik', 'förlag', 'nyheter'],
  'TV och radio': ['media', 'journalistik', 'broadcast'],
  'Trädgårdsskötsel och park': ['trädgård', 'park', 'grönyta', 'anläggare'],
  'Tvättservice och kemtvätt': ['tvätteri', 'kemtvätt'],
  'Återvinning och avfallshantering': ['avfall', 'sophämtning', 'återvinning', 'miljö'],
  'Översättning och tolkning': ['tolk', 'översättare', 'språk'],
  'Yrkeshögskola': ['YH', 'utbildning', 'skola'],
  'Kasinon och spel': ['gaming', 'spel', 'casino', 'betting'],
  'Leksaker och spel': ['leksaker', 'handel', 'spel'],
  'Sport och fritid handel': ['sport', 'butik', 'handel'],
  'Byggmaterial handel': ['bygg', 'bygghandel', 'handel'],
  'Kryssningar och båtturer': ['båt', 'turism', 'rederi'],
  'Nöjesparker och attraktioner': ['nöjespark', 'turism', 'event'],
  'Kärnkraft': ['energi', 'kraft', 'kärnkraftverk'],
  'Olja och petroleum': ['energi', 'olja', 'raffinaderi'],
  'Vattenförsörjning': ['vatten', 'VA', 'kommun'],
};


/** Branschsökning: smart sökning på både namn och alias. */
export const matchesIndustry = (
  term: string,
  option: string,
  smartMatches: (q: string, fields: string[]) => boolean,
): boolean => smartMatches(term, [option, ...(INDUSTRY_ALIASES[option] ?? [])]);
