export const SWEDISH_INDUSTRIES = [
  'Alternativ medicin',
  'Anläggningsbyggnad',
  'Annat',
  'Apotek',
  'Apotek och hälsokost',
  'Apputveckling',
  'Arbetsförmedling',
  'Arbetsterapi',
  'Arkitektur och design',
  'Avloppsrening',
  'Banker',
  'Barer och pubar',
  'Barnomsorg och förskola',
  'Barnpassning',
  'Begravningsbyråer',
  'Bemanningsbranschen',
  'Biodling',
  'Bibliotek',
  'Blommor och trädgård',
  'Blomsterodling',
  'Bokförlag',
  'Bokhandel och papper',
  'Bostadsrättsföreningar',
  'Brandkår och räddningstjänst',
  'Branschorganisationer',
  'Bröllopsarrangörer',
  'Bygg och trädgård handel',
  'Byggmaterial handel',
  'Bärodling',
  'Camping och stugor',
  'Cybersäkerhet',
  'Dagligvaruhandel',
  'Databaser och servrar',
  'Dietist och näring',
  'Digital marknadsföring',
  'Djur och djurtillbehör',
  'Drivmedel och bensinstationer',
  'Dryckesproduktion',
  'E-learning och distansutbildning',
  'Ekonomisk rådgivning',
  'Ekologisk odling',
  'Elektronik och halvledare',
  'Elektronik och vitvaror',
  'Elinstallation',
  'Elproduktion och distribution',
  'Factoring och leasing',
  'Facility management',
  'Fackföreningar',
  'Familjerådgivning',
  'Fastighetsfonder',
  'Fastighetsmäkleri',
  'Fastighetstaxering',
  'Fastighetsutveckling',
  'Fastighetsförvaltning',
  'Festivaler och event',
  'Film och TV-produktion',
  'Fiske och vattenbruk',
  'Fjärrvärme och kyla',
  'Flygtransport och flygplatser',
  'Flyktingmottagning',
  'Fordon och reservdelar',
  'Fordonsindustri',
  'Forskning och utveckling',
  'Fotostudios',
  'Frisörsalonger',
  'Fruktodling',
  'Funktionshinderomsorg',
  'Fysioterapi och sjukgymnastik',
  'Företagsutbildning',
  'Förnybar energi',
  'Förskola',
  'Försäkringsbolag',
  'Försäkringskassan',
  'Försvar och militär',
  'Gasförsörjning',
  'Glas, keramik och cement',
  'Golv och kakel',
  'Grafisk design',
  'Grosshandel',
  'Grundskola',
  'Gruvdrift och utvinning',
  'Grönsaksodling',
  'Gymnasium',
  'Handikappomsorg',
  'Heminredning och möbler',
  'Hemsjukvård',
  'Hemlöshetsstöd',
  'Hotell och logi',
  'HR-konsulting',
  'HR-tjänster',
  'Hundpensionat och hunddagis',
  'Husbyggnad',
  'Hushållstjänster',
  'Hästhållning och ridskolor',
  'Idrottsanläggningar',
  'Idrottsskolor',
  'Ingenjörstjänster',
  'Internationella organisationer',
  'Internetleverantörer',
  'Investmentbolag',
  'IT-konsulting',
  'Jordbruk och trädgård',
  'Juridik och advokatbyråer',
  'Järnvägstransport',
  'Kafé och konditori',
  'Kasinon och spel',
  'Kemisk industri',
  'Kläder och skor',
  'Kollektivtrafik',
  'Kommunal förvaltning',
  'Komvux och vuxenutbildning',
  'Konferens och event',
  'Konsultförmedling',
  'Konsumentkooperativ',
  'Konsthantverk',
  'Konstskolor',
  'Kreditinstitut',
  'Kryssningar och båtturer',
  'Kurirtjänster och post',
  'Körskolor',
  'Köttproduktion',
  'Kärnkraft',
  'Laboratoriverksamhet',
  'Lastbilstransport',
  'Leksaker och spel',
  'Livsmedelsproduktion',
  'Läkemedel och bioteknik',
  'Magasinering och lager',
  'Managementkonsulting',
  'Marknadsanalys',
  'Maskintillverkning',
  'Massage och terapi',
  'Medicinsk forskning',
  'Medieproduktion',
  'Medlemsorganisationer',
  'Metall och metallbearbetning',
  'Migrationsverket',
  'Miljökonsulting',
  'Missbruksvård',
  'Mjukvaruutveckling',
  'Mjölkproduktion',
  'Musik och konsert',
  'Musikskolor',
  'Museer och gallerier',
  'Mäkleri och värdepapper',
  'Måleri och puts',
  'Möbler och inredning',
  'Nagelstudios',
  'Nöjesparker',
  'Nöjesparker och attraktioner',
  'Olja och petroleum',
  'Optisk och medicinteknisk utrustning',
  'Papper och förpackning',
  'Pensionsfonder',
  'Pensionsmyndighet',
  'Personaluthyrning',
  'Personlig träning',
  'Plast och gummi',
  'Polis och rättsväsen',
  'Politiska partier',
  'PR och kommunikation',
  'Projektledning',
  'Psykiatri och psykologi',
  'Pälsdjursuppfödning',
  'Redovisning och bokföring',
  'Regionförvaltning',
  'Rekrytering och headhunting',
  'Reklam och marknadsföring',
  'Religiösa organisationer',
  'Reparationer och service',
  'Resebyråer och guider',
  'Restauranger och catering',
  'Revision',
  'Rivning och sanering',
  'Rörledningar',
  'Samfälligheter',
  'Second hand och antikviteter',
  'Sjukhus',
  'Sjöfart och hamnar',
  'Skattemyndighet',
  'Skatterådgivning',
  'Skogsbruk',
  'Skönhetssalonger',
  'Snabbmat och gatukök',
  'Snöröjning och vinterservice',
  'Socialtjänst',
  'Spa och wellness',
  'Spannmålsodling',
  'Specialbyggnad',
  'Specialistmottagningar',
  'Spedition och frakt',
  'Sport och fritid handel',
  'Sportklubbar och gym',
  'Språkskolor',
  'Statlig förvaltning',
  'Stiftelser och ideell sektor',
  'Städ och renhållning',
  'Systemintegration',
  'Säkerhet och bevakning',
  'Tandvård',
  'Taxi och biltjänster',
  'Teater och scen',
  'Teknisk konsulting',
  'Telekommunikation',
  'Temp-anställningar',
  'Textil och beklädnad',
  'Tidningar och förlag',
  'Trä- och möbelindustri',
  'Trädgårdsskötsel och park',
  'Tullverket',
  'TV och radio',
  'Tvättservice och kemtvätt',
  'Universitet och högskola',
  'Vattenförsörjning',
  'Veterinärvård',
  'VVS-installation',
  'Volontärorganisationer',
  'Vårdcentraler',
  'Växthusodling',
  'Webbutveckling',
  'Yrkeshögskola',
  'Återvinning och avfallshantering',
  'Äldreomsorg',
  'Översättning och tolkning',
  'Äggproduktion'
];

export const EMPLOYEE_COUNT_OPTIONS = [
  '1-10 anställda',
  '11-50 anställda',
  '51-200 anställda',
  '201-500 anställda',
  '500+ anställda'
];