// Swedish occupations structure - synchronized with SearchJobs.tsx
export interface OccupationCategory {
  value: string;
  label: string;
  keywords: string[];
  subcategories: string[];
}

export const OCCUPATION_CATEGORIES: OccupationCategory[] = [
  { 
    value: 'administration', 
    label: 'Administration, Ekonomi, Juridik',
    keywords: ['administration', 'ekonomi', 'redovisning', 'controller', 'assistent', 'sekreterare', 'koordinator', 'projektledare', 'juridik', 'advokat', 'receptionist', 'administratör'],
    subcategories: [
      'Administratör',
      'Advokat',
      'Affärs- och företagsjurist',
      'Affärscoach',
      'Arbetsmärke',
      'Arkiv- och biblioteksassistent m.fl.',
      'Backofficespecialist m.fl.',
      'Business Analyst',
      'Chefssekreterare och VD-assistent m.fl.',
      'Controller',
      'Domare',
      'Domstols- och juristsekreterare m.fl.',
      'Ekonomiassistent m.fl.',
      'Event Coordinator',
      'Finansanalytiker och investeringsrådgivare m.fl.',
      'Försäkringssäljare och försäkringsrådgivare',
      'Förvaltnings- och organisationsjurist',
      'Gruppledare för kontorspersonal',
      'Informatör, kommunikatör och PR-specialist',
      'Inkasserare och pantlånare m.fl.',
      'Kontorsreceptionist',
      'Koordinator',
      'Lednings- och organisationsutvecklare',
      'Management Consultant',
      'Medicinska sekreterare, vårdadministratör m.fl.',
      'Mäklare inom finans',
      'Nationalekonomer och makroanalytiker m.fl.',
      'Personal- och HR-specialist',
      'Personlig assistent',
      'Planerade och utredare m.fl.',
      'Receptionist',
      'Redovisningsekonom',
      'Revisor m.fl.',
      'Skadereglerare och värderare',
      'Skatthandläggare',
      'Socialförsäkringshandläggare',
      'Statistiker',
      'Telefonist',
      'Trader och fondförvaltare',
      'Virtual Assistant',
      'Åklagare',
      'Övrig ekonom',
      'Övrig handläggare',
      'Övrig jurist',
      'Övriga kontorsassistent och sekreterare'
    ]
  },
  { 
    value: 'construction', 
    label: 'Bygg och Anläggning', 
    keywords: ['bygg', 'snickare', 'elektriker', 'anläggning', 'murare', 'målare', 'byggledare', 'platschef', 'vvs'],
    subcategories: [
      'Anläggningsarbetare',
      'Anläggningsdykare',
      'Anläggningsmaskinförare m.fl.',
      'Arbetsledare inom bygg, anläggning och gruva',
      'Betongarbetare',
      'Brunnsborrare m.fl.',
      'Bygnads- och ventilationsplåtslagare',
      'Civilingenjörsyrken inom bygg och anläggning',
      'Golvläggare',
      'Grovarbetare inom bygg och anläggning',
      'Gruv- och stenbrottsarbetare',
      'Ingenjörer och tekniker inom bygg och anläggning',
      'Isoleringsmontör',
      'Kranförare m.fl.',
      'Kyl- och värmepumpstekniker m.fl.',
      'Murare m.fl.',
      'Målare',
      'Stallningsbyggare',
      'Takmontör',
      'Träarbetare, snickare m.fl.',
      'VVS-montör m.fl.',
      'Övrig byggnads- och anläggningsarbetare'
    ]
  },
  { 
    value: 'management', 
    label: 'Chefer och Verksamhetsledare', 
    keywords: ['chef', 'ledare', 'verksamhet', 'director', 'manager', 'vd', 'platschef', 'avdelningschef', 'teamledare', 'team leader'],
    subcategories: [
      'Chefer inom arkitekt- och ingenjörsverksamhet',
      'Chefer inom bank, finans och försäkring',
      'Chefer inom friskvård, sport och fritid',
      'Chefer inom förskolverksamhet',
      'Chefer inom grund- och gymnasieskola samt vuxenutbildning',
      'Chefer inom handel',
      'Chefer inom hälso- och sjukvård',
      'Chefer inom socialt och kurativt arbete',
      'Chefer inom äldreomsorg',
      'Chefer och ledare inom trossamfund',
      'Chefstjänstemän i intresseorganisationer',
      'Driftchefer inom bygg, anläggning och gruva',
      'Ekonomi- och finanschefer',
      'Fastighets- och förvaltningschefer',
      'Forsknings- och utvecklingschefer',
      'Försäljnings- och marknadschefer',
      'Förvaltare inom skogsbruk och lantbruk m.fl.',
      'General-, landstings- och kommundirektörer m.fl.',
      'Hotell- och konferenschefer',
      'IT-chefer',
      'Informations-, kommunikations- och PR-chefer',
      'Inköps-, logistik- och transportchefer',
      'Personal- och HR-chefer',
      'Politiker',
      'Produktionschefer inom tillverkning',
      'Restaurang- och kökchefer',
      'Teamledare',
      'Verkställande direktörer m.fl.',
      'Övriga administrations- och servicechefer',
      'Övriga chefer inom samhällsservice',
      'Övriga chefer inom utbildning',
      'Övriga chefer inom övrig servicenäring'
    ]
  },
  { 
    value: 'it', 
    label: 'Data/IT', 
    keywords: ['utvecklare', 'programmerare', 'IT', 'data', 'systemadministratör', 'webb', 'mjukvara', 'frontend', 'backend', 'fullstack', 'devops', 'cybersäkerhet', 'product manager', 'scrum', 'cloud', 'ux', 'ui'],
    subcategories: [
      'Cloud Architect',
      'Data Analyst',
      'DevOps Engineer',
      'Drifttekniker, IT',
      'IT-säkerhetsspecialister',
      'Mjukvaru- och systemutvecklare m.fl.',
      'Nätverks- och systemtekniker m.fl.',
      'Product Manager',
      'Scrum Master',
      'Supporttekniker, IT',
      'Systemadministratörer',
      'Systemanalytiker och IT-arkitekter m.fl.',
      'Systemförvaltare m.fl.',
      'Systemtestare och testledare',
      'UX/UI Designer',
      'Utvecklare inom spel och digitala media',
      'Webbmaster och webbadministratörer',
      'Övriga IT-specialister'
    ]
  },
  { 
    value: 'sales', 
    label: 'Försäljning, Inköp, Marknadsföring', 
    keywords: ['försäljning', 'sales', 'säljare', 'account', 'marketing', 'marknadsföring', 'reklam', 'kommunikation', 'pr', 'inköp', 'digital marketing', 'seo', 'social media', 'ecommerce'],
    subcategories: [
      'Apotekstekniker',
      'Banktjänstemän',
      'Bensinstationspersonal',
      'Butikschef',
      'Butikssäljare, dagligvaror',
      'Butikssäljare, fackhandel',
      'Digital Marketing Specialist',
      'E-commerce Manager',
      'Evenemangs- och reseproducenter m.fl.',
      'Eventsäljare och butiksdemonistratörer m.fl.',
      'Fastighetsmäklare',
      'Företagssäljare',
      'Guider och resetedare',
      'Inköpare och upphandlare',
      'Inköps- och orderassistenter',
      'Kassapersonal m.fl.',
      'Kundtjänstpersonal',
      'Marknads- och försäljningsassistenter',
      'Marknadsanalytiker och marknadsförare m.fl.',
      'Marknadsundersökare och intervjuare',
      'Optikerassistenter',
      'Ordersamordnare m.fl.',
      'Resesäljare och trafikassistenter m.fl.',
      'SEO Specialist',
      'Social Media Manager',
      'Speditörer och transportmäklare',
      'Säljande butikschefer och avdelningschefer i butik',
      'Telefonförsäljare m.fl.',
      'Torg- och marknadsförsäljare m.fl.',
      'Uthyrare',
      'Visual Merchandiser',
      'Övriga förmedlare'
    ]
  },
  { 
    value: 'crafts', 
    label: 'Hantverkyrken', 
    keywords: ['hantverk', 'smed', 'keramiker', 'snickare', 'träarbete', 'metallarbete', 'bagare', 'konditor'],
    subcategories: [
      'Bagare och konditorer',
      'Fin-, inrednings- och möbelsnickare',
      'Finmekaniker',
      'Glastekniker',
      'Guld- och silversmeder',
      'Läderhantverkare och skomakare',
      'Manuella ytbehandlare, trä',
      'Musikinstrumentmakare och övriga konsthantverkare',
      'Skräddare och ateljésömmerskor m.fl.',
      'Smeder',
      'Sömmare',
      'Tapetserare'
    ]
  },
  { 
    value: 'restaurant', 
    label: 'Hotell, Restaurang, Storhushåll', 
    keywords: ['kock', 'servitör', 'hotell', 'restaurang', 'storhushåll', 'bagare', 'konditor', 'hovmästare', 'barista', 'catering'],
    subcategories: [
      'Barista',
      'Bartender',
      'Cateringpersonal',
      'Croupierer och oddssättare m.fl.',
      'Hotellreceptionist m.fl.',
      'Hovmästare och servitör',
      'Kafé- och konditorbiträden',
      'Kock och kallskänka',
      'Köksmästare och souschefer',
      'Pizzabagare m.fl.',
      'Restaurang- och köksbiträden m.fl.',
      'Storhushållsföreståndare'
    ]
  },
  { 
    value: 'healthcare', 
    label: 'Hälso- och Sjukvård', 
    keywords: ['sjuksköterska', 'läkare', 'vård', 'omsorg', 'tandläkare', 'fysioterapeut', 'undersköterska', 'vårdbiträde', 'nutrition', 'kostrådgivare', 'personal trainer', 'life coach'],
    subcategories: [
      'AT-läkare',
      'Ambulanssjuksköterska m.fl.',
      'Ambulanssjukvårdare',
      'Anestesisjuksköterska',
      'Apotekare',
      'Arbetsterapeut',
      'Audionomer och logoped',
      'Barnmorska',
      'Barnsjuksköterska',
      'Barnsköterska',
      'Biomedicinsk analytiker m.fl.',
      'Dietist',
      'Distriktsjuksköterska',
      'Djursjuksköterska m.fl.',
      'Fysioterapeut och sjukgymnast',
      'Företagsjuksköterska',
      'Geriatriksjuksköterska',
      'Grundutbildad sjuksköterska',
      'Hemtjänstpersonal',
      'Intensivvårdssjuksköterska',
      'Kiropraktor och naprapater m.fl.',
      'Kostrådgivare',
      'Life Coach',
      'Nutritionist',
      'Operationssjuksköterska',
      'Optiker',
      'Personlig tränare',
      'Psykiatrisjuksköterska',
      'Psykolog',
      'Psykoterapeut',
      'Receptarier',
      'Röntgensjuksköterska',
      'ST-läkare',
      'Skolsjuksköterska',
      'Skötare',
      'Specialistläkare',
      'Tandhygienist',
      'Tandläkare',
      'Tandsköterska',
      'Terapeut inom alternativmedicin',
      'Undersköterska, hemsjukvård, äldreboende och habilitering',
      'Undersköterska, vård- och specialavdelning och mottagning',
      'Veterinär',
      'Vårdbiträden',
      'Övrig vård- och omsorgspersonal',
      'Övrig läkare',
      'Övrig specialist inom hälso- och sjukvård',
      'Övrig specialistsjuksköterska'
    ]
  },
  { 
    value: 'industry', 
    label: 'Industriell Tillverkning', 
    keywords: ['industri', 'tillverkning', 'produktion', 'maskinoperatör', 'kvalitet', 'process', 'tekniker'],
    subcategories: [
      'Arbetsledare inom tillverkning',
      'Bergsprängare',
      'Bobindare m.fl.',
      'Fordonsmontörer',
      'Gjutare',
      'Handpaketerare och andra fabriksarbetare',
      'Lackerare och industrimålare',
      'Maskinoperatör inom ytbehandling, trä',
      'Maskinoperatör, blekning, färgning och tvättning',
      'Maskinoperatör, cement-, sten- och betongvaror',
      'Maskinoperatör, farmaceutiska produkter',
      'Maskinoperatör, gummiindustri',
      'Maskinoperatör, kemisktekniska och fotografiska produkter',
      'Maskinoperatör, kvarn-, bageri- och konfektyrindustri',
      'Maskinoperatör, kött- och fiskberedningsindustri',
      'Maskinoperatör, mejeri',
      'Maskinoperatör, plastindustri',
      'Maskinoperatör, pappersvaruindustri',
      'Maskinoperatör, pappersindustri',
      'Maskinoperatör, påfyllning, packning och märkning',
      'Maskinställare och maskinoperatör, metallarbete',
      'Maskinsnickare och maskinoperatör, träindustri',
      'Montör, elektrisk och elektronisk utrustning',
      'Montör, metall-, gummi- och plastprodukter',
      'Montör, träprodukter',
      'Operatör inom sågverk, hyvleri och plywood m.m.',
      'Prepress tekniker',
      'Processoperatör, papper',
      'Processoperatör, pappersmassa',
      'Processoperatör, stenkross- och malmförädling',
      'Provsmakare och kvalitetsbedömare',
      'Slaktare och styckare m.fl.',
      'Slipare m.fl.',
      'Stenhuggare m.fl.',
      'Stålkonstruktionsmontör och grovplåtslagare',
      'Svetsare och gasskärare',
      'Tryckare',
      'Tunnplåtslagare',
      'Valsverksoperatör',
      'Verktygsmakare',
      'Övrig maskin- och processoperatör vid stål- och metallverk',
      'Övrig maskinoperatör, livsmedelsindustri m.m.',
      'Övrig maskinoperatör, textil-, skinn- och läderindustri',
      'Övrig montör',
      'Övrig process- och maskinoperatör'
    ]
  },
  { 
    value: 'installation', 
    label: 'Installation, Drift, Underhåll', 
    keywords: ['installation', 'drift', 'underhåll', 'reparatör', 'tekniker', 'service', 'elektriker', 'fastighet'],
    subcategories: [
      'Distributionselektriker',
      'Drifttekniker vid värme- och vattenverk',
      'Elektronikreparatör och kommunikationselektriker m.fl.',
      'Fastighetsskötare',
      'Flygmekaniker m.fl.',
      'Industrielektriker',
      'Installations- och serviceelektriker',
      'Motorfordonsmekaniker och fordonsreparatör',
      'Processövervakare, kemisk industri',
      'Processövervakare, metallproduktion',
      'Underhållsmekaniker och maskinreparatör',
      'Vaktmästare m.fl.',
      'Övrig drifttekniker och processövervakare',
      'Övrig servicearbetare'
    ]
  },
  { 
    value: 'logistics', 
    label: 'Transport', 
    keywords: ['lager', 'logistik', 'transport', 'distribution', 'chaufför', 'lastbil', 'gaffeltruck', 'leverans', 'kurir', 'bud', 'uber', 'drönare', 'drone'],
    subcategories: [
      'Arbetsledare inom lager och terminal',
      'Bangårdspersonal', 
      'Brevbärare och postterminalarbetare',
      'Budbilsförare',
      'Buss- och spårvagnsförare',
      'Distributionschaufför',
      'Drone Pilot',
      'Fartygsbefäl m.fl.',
      'Flygledare',
      'Hamnarbetare',
      'Kabinpersonal m.fl.',
      'Kurir',
      'Lager- och terminalpersonal', 
      'Lastbilsförare m.fl.',
      'Lokförare',
      'Maskinbefäl',
      'Matros och jungman m.fl.',
      'Pilot m.fl.',
      'Ramppersonal, flyttkarlar och varupåfyllare m.fl.',
      'Reklamutdelare och tidningsdistributör',
      'Taxiförare m.fl.',
      'Transportledare och transportsamordnare',
      'Truckförare',
      'Tågvärd och ombordansvarig m.fl.',
      'Uber-förare'
    ]
  },
  { 
    value: 'beauty', 
    label: 'Kropps- och Skönhetsvård', 
    keywords: ['frisör', 'skönhet', 'massage', 'naglar', 'kosmetolog', 'fotvård', 'hudterapeut', 'makeup', 'tatuering'],
    subcategories: [
      'Fotterapeut',
      'Frisör',
      'Hudterapeut',
      'Makeup Artist',
      'Massör och massageterapeut',
      'Tatuerare',
      'Övrig skönhets- och kroppsterapeut'
    ]
  },
  { 
    value: 'creative', 
    label: 'Kultur, Media, Design', 
    keywords: ['design', 'grafisk', 'kreativ', 'media', 'journalist', 'fotograf', 'video', 'kultur', 'konstnär', 'bibliotek', 'content', 'influencer', 'podcast', 'streaming', 'esport', 'gaming'],
    subcategories: [
      'Bibliotekarie och arkivarie',
      'Bild- och sandningstekniker',
      'Bildkonstnär m.fl.',
      'Content Creator',
      'Designer inom spel och digitala medier',
      'E-sports spelare',
      'Fotograf',
      'Författare m.fl.',
      'Grafisk formgivare m.fl.',
      'Industridesigner',
      'Influencer',
      'Inredare, dekoratörer och scenografer m.fl.',
      'Inspicienter och scriptör m.fl.',
      'Journalist m.fl.',
      'Koreograf och dansare',
      'Ljus-, ljud- och scentekniker',
      'Museiintendent m.fl.',
      'Musiker, sångare och kompositör',
      'Podcaster',
      'Regissör och producenter av film, teater m.m.',
      'Skådespelare',
      'Streamer',
      'Översättare, tolk och lingvist m.fl.',
      'Övrig designer och formgivare',
      'Övrig yrken inom kultur och underhållning'
    ]
  },
  { 
    value: 'military', 
    label: 'Militärt Arbete', 
    keywords: ['militär', 'försvar', 'soldat', 'officer', 'specialistofficerare'],
    subcategories: [
      'Officer',
      'Soldat m.fl.',
      'Specialistofficer'
    ]
  },
  { 
    value: 'agriculture', 
    label: 'Naturbruk', 
    keywords: ['lantbruk', 'jordbruk', 'skog', 'djur', 'trädgård', 'fiske', 'skogsarbete', 'hundvakt', 'djurpassning'],
    subcategories: [
      'Bärplockare och plantör m.fl.',
      'Djurpassare',
      'Fiskare',
      'Fiskodlare',
      'Förare av jordbruks- och skogsmaskin',
      'Hundvakt',
      'Odlare av jordbruksväxter, frukt och bär',
      'Skogsarbetare',
      'Specialist och rådgivare inom lantbruk m.m.',
      'Specialist och rådgivare inom skogsbruk',
      'Trädgårdsanläggare m.fl.',
      'Trädgårdsodlare',
      'Uppfödare och skötare av lantbrukets husdjur',
      'Uppfödare och skötare av sällskapsdjur',
      'Växtodlare och djuruppfödare, blandad drift',
      'Övrig djuruppfödare och djurskötare'
    ]
  },
  { 
    value: 'science', 
    label: 'Naturvetenskapligt Arbete', 
    keywords: ['forskning', 'vetenskap', 'laboratorium', 'kemi', 'biologi', 'fysik', 'matematik'],
    subcategories: [
      'Cell- och molekylärbiolog m.fl.',
      'Farmakolog och biomedicinare',
      'Fysiker och astronom',
      'Geolog och geofysiker m.fl.',
      'Kemist',
      'Matematiker och aktuarie',
      'Meteorolog',
      'Miljö- och hälsoskyddsinspektör',
      'Specialist inom miljöskydd och miljöteknik',
      'Växt- och djurbiolog'
    ]
  },
  { 
    value: 'education', 
    label: 'Pedagogiskt Arbete', 
    keywords: ['lärare', 'utbildning', 'skola', 'universitet', 'förskola', 'pedagog', 'barnskötare', 'fritidsledare'],
    subcategories: [
      'Doktorand',
      'Elevassistent m.fl.',
      'Forskarassistent m.fl.',
      'Fritidspedagog',
      'Förskollärare',
      'Grundskollärare',
      'Gymnasielärare',
      'Idrottstränare och instruktör m.fl.',
      'Lärare i yrkesämnen',
      'Professionell idrottutövare',
      'Professor',
      'Speciallärare och specialpedagog m.fl.',
      'Studie- och yrkesvägledare',
      'Trafiklarare',
      'Universitets- och högskolelektor',
      'Övrig pedagog med teoretisk specialistkompetens',
      'Övrig universitets- och högskolelärare',
      'Övrig utbildare och instruktör'
    ]
  },
  { 
    value: 'cleaning', 
    label: 'Sanering och Renhållning', 
    keywords: ['städ', 'rengöring', 'sanering', 'renhållning', 'lokalvård', 'skorstensfejare', 'hemstäd'],
    subcategories: [
      'Bilrekonditionerare, fönsterputsare m.fl.',
      'Hemstädare',
      'Renhållnings- och återvinningsarbetare',
      'Renhållningschaufför',
      'Saneringsarbetare m.fl.',
      'Skorstensfjejare',
      'Städare',
      'Städledare och husfruar',
      'Övrig hemservicepersonal m.fl.'
    ]
  },
  { 
    value: 'security', 
    label: 'Säkerhet och Skydd', 
    keywords: ['säkerhet', 'vakt', 'väktare', 'brandman', 'skydd', 'bevakning', 'polis', 'ordning'],
    subcategories: [
      'Arbetsmiljöingenjörer, yrkes- och miljöhygieniker',
      'Brandingenjörer och byggnadsinspektörer m.fl.',
      'Brandmän',
      'Kriminalvårdare',
      'Polis',
      'SOS-operatörer m.fl.',
      'Säkerhetsinspektörer m.fl.',
      'Säkerhetsvakt',
      'Tull- och kustbevakningtjänstemän',
      'Väktare och ordningsvakter',
      'Övrig bevaknings- och säkerhetspersonal'
    ]
  },
  { 
    value: 'social',
    label: 'Socialt Arbete', 
    keywords: ['social', 'socialtjänst', 'stöd', 'hjälp', 'omsorg', 'kurator', 'behandling'],
    subcategories: [
      'Barnskötare',
      'Begravnings- och krematoriepersonal',
      'Behandlingsassistent och socialpedagog m.fl.',
      'Biståndshandläggare m.fl.',
      'Diakoner',
      'Friskvårdskonsulent och hälsopedagog m.fl.',
      'Fritidsledare m.fl.',
      'Kurator',
      'Pastorer m.fl.',
      'LSS-assistent',
      'Präster',
      'Socialsekreterare',
      'Vårdare, boendestödjare',
      'Övrig servicepersonal',
      'Övrig yrke inom socialt arbete'
    ]
  },
  { 
    value: 'technical', 
    label: 'Tekniskt Arbete',
    keywords: ['ingenjör', 'tekniker', 'konstruktör', 'design', 'utveckling', 'arkitekt', 'civilingenjör'],
    subcategories: [
      'Arkitekt m.fl.',
      'Civilingenjörsyrken inom elektroteknik',
      'Civilingenjörsyrken inom gruvteknik och metallurgi',
      'Civilingenjörsyrken inom kemi och kemiteknik',
      'Civilingenjörsyrken inom logistik och produktionsplanering',
      'Civilingenjörsyrken inom maskinteknik',
      'Fastighetsförvaltare',
      'Flygtekniker',
      'GIS- och kartingenjör',
      'Ingenjör och tekniker inom elektroteknik',
      'Ingenjör och tekniker inom gruvteknik och metallurgi',
      'Ingenjör och tekniker inom industri, logistik och produktionsplanering',
      'Ingenjör och tekniker inom kemi och kemiteknik',
      'Ingenjör och tekniker inom maskinteknik',
      'Laboratorieingenjör',
      'Landskapsarkitekt',
      'Lantmätare',
      'Planeringsarkitekter m.fl.',
      'Tandtekniker och ortopedingenjörer m.fl.',
      'Tekniker, bilddiagnostik och medicinteknisk utrustning',
      'Övrig civilingenjörsyrke',
      'Övrig ingenjör och tekniker'
    ]
  }
];

// Get all occupations as a flat list for search functionality
export const getAllOccupations = (): string[] => {
  const allOccupations: string[] = [];
  OCCUPATION_CATEGORIES.forEach(category => {
    allOccupations.push(...category.subcategories);
  });
  return allOccupations.sort();
};

// Search occupations by term
export const searchOccupations = (searchTerm: string): string[] => {
  if (!searchTerm || searchTerm.length < 2) {
    return [];
  }
  
  const term = searchTerm.toLowerCase();
  const allOccupations = getAllOccupations();
  
  return allOccupations.filter(occupation => 
    occupation.toLowerCase().includes(term)
  ).slice(0, 10); // Limit to 10 results
};