// Swedish occupations structure - synchronized with SearchJobs.tsx
export interface OccupationCategory {
  value: string;
  label: string;
  keywords: string[];
  subcategories: string[];
}

export const OCCUPATION_CATEGORIES: OccupationCategory[] = [
  { 
    value: 'administration', 
    label: 'Administration, Ekonomi, Juridik',
    keywords: ['administration', 'ekonomi', 'redovisning', 'controller', 'assistent', 'sekreterare', 'koordinator', 'projektledare', 'juridik', 'advokat', 'receptionist', 'administratör'],
    subcategories: [
      'Administratör',
      'Advokater',
      'Affärs- och företagsjurister',
      'Affärscoach',
      'Arbetsmärke',
      'Arkivvård- och biblioteksassistenter m.fl.',
      'Arkiv- och biblioteksassistenter m.fl.',
      'Backofficespecialister m.fl.',
      'Business Analyst',
      'Chefssekreterare och VD-assistenter m.fl.',
      'Controller',
      'Domare',
      'Domstols- och juristsekreterare m.fl.',
      'Ekonomiassistenter m.fl.',
      'Event Coordinator',
      'Finansanalytiker och investeringsrådgivare m.fl.',
      'Försäkringssäljare och försäkringsrådgivare',
      'Förvaltnings- och organisationsjurister',
      'Gruppledare för kontorspersonal',
      'Informatörer, kommunikatörer och PR-specialister',
      'Inkasserare och pantlånare m.fl.',
      'Kontorsreceptionister',
      'Koordinator',
      'Lednings- och organisationsutvecklare',
      'Management Consultant',
      'Medicinska sekreterare, vårdadministratörer m.fl.',
      'Mäklare inom finans',
      'Nationalekonomer och makroanalytiker m.fl.',
      'Personal- och HR-specialister',
      'Personlig assistent',
      'Planerade och utredare m.fl.',
      'Receptionist',
      'Redovisningsekonomer',
      'Revisorer m.fl.',
      'Skadereglerare och värderare',
      'Skatthandläggare',
      'Socialförsäkringshandläggare',
      'Statistiker',
      'Telefonister',
      'Traders och fondförvaltare',
      'Virtual Assistant',
      'Åklagare',
      'Övriga ekonomer',
      'Övriga handläggare',
      'Övriga jurister',
      'Övriga kontorsassistenter och sekreterare'
    ]
  },
  { 
    value: 'construction', 
    label: 'Bygg och Anläggning', 
    keywords: ['bygg', 'snickare', 'elektriker', 'anläggning', 'murare', 'målare', 'byggledare', 'platschef', 'vvs'],
    subcategories: [
      'Anläggningsarbetare',
      'Anläggningsdykare',
      'Anläggningsmaskinförare m.fl.',
      'Arbetsledare inom bygg, anläggning och gruva',
      'Betongarbetare',
      'Brunnsborrare m.fl.',
      'Bygnads- och ventilationsplåtslagare',
      'Civilingenjörsyrken inom bygg och anläggning',
      'Golvläggare',
      'Grovarbetare inom bygg och anläggning',
      'Gruv- och stenbrottsarbetare',
      'Ingenjörer och tekniker inom bygg och anläggning',
      'Isoleringsmontörer',
      'Kranförare m.fl.',
      'Kyl- och värmepumpstekniker m.fl.',
      'Murare m.fl.',
      'Målare',
      'Stallningsbyggare',
      'Takmontörer',
      'Träarbetare, snickare m.fl.',
      'VVS-montörer m.fl.',
      'Övriga byggnads- och anläggningsarbetare'
    ]
  },
  { 
    value: 'management', 
    label: 'Chefer och Verksamhetsledare', 
    keywords: ['chef', 'ledare', 'verksamhet', 'director', 'manager', 'vd', 'platschef', 'avdelningschef', 'teamledare', 'team leader'],
    subcategories: [
      'Chefer inom arkitekt- och ingenjörsverksamhet',
      'Chefer inom bank, finans och försäkring',
      'Chefer inom friskvård, sport och fritid',
      'Chefer inom förskolverksamhet',
      'Chefer inom grund- och gymnasieskola samt vuxenutbildning',
      'Chefer inom handel',
      'Chefer inom hälso- och sjukvård',
      'Chefer inom socialt och kurativt arbete',
      'Chefer inom äldreomsorg',
      'Chefer och ledare inom trossamfund',
      'Chefstjänstemän i intresseorganisationer',
      'Driftchefer inom bygg, anläggning och gruva',
      'Ekonomi- och finanschefer',
      'Fastighets- och förvaltningschefer',
      'Forsknings- och utvecklingschefer',
      'Försäljnings- och marknadschefer',
      'Förvaltare inom skogsbruk och lantbruk m.fl.',
      'General-, landstings- och kommundirektörer m.fl.',
      'Hotell- och konferenschefer',
      'IT-chefer',
      'Informations-, kommunikations- och PR-chefer',
      'Inköps-, logistik- och transportchefer',
      'Personal- och HR-chefer',
      'Politiker',
      'Produktionschefer inom tillverkning',
      'Restaurang- och kökchefer',
      'Teamledare',
      'Verkställande direktörer m.fl.',
      'Övriga administrations- och servicechefer',
      'Övriga chefer inom samhällsservice',
      'Övriga chefer inom utbildning',
      'Övriga chefer inom övrig servicenäring'
    ]
  },
  { 
    value: 'it', 
    label: 'Data/IT', 
    keywords: ['utvecklare', 'programmerare', 'IT', 'data', 'systemadministratör', 'webb', 'mjukvara', 'frontend', 'backend', 'fullstack', 'devops', 'cybersäkerhet', 'product manager', 'scrum', 'cloud', 'ux', 'ui'],
    subcategories: [
      'Cloud Architect',
      'Data Analyst',
      'DevOps Engineer',
      'Drifttekniker, IT',
      'IT-säkerhetsspecialister',
      'Mjukvaru- och systemutvecklare m.fl.',
      'Nätverks- och systemtekniker m.fl.',
      'Product Manager',
      'Scrum Master',
      'Supporttekniker, IT',
      'Systemadministratörer',
      'Systemanalytiker och IT-arkitekter m.fl.',
      'Systemförvaltare m.fl.',
      'Systemtestare och testledare',
      'UX/UI Designer',
      'Utvecklare inom spel och digitala media',
      'Webbmaster och webbadministratörer',
      'Övriga IT-specialister'
    ]
  },
  { 
    value: 'sales', 
    label: 'Försäljning, Inköp, Marknadsföring', 
    keywords: ['försäljning', 'sales', 'säljare', 'account', 'marketing', 'marknadsföring', 'reklam', 'kommunikation', 'pr', 'inköp', 'digital marketing', 'seo', 'social media', 'ecommerce'],
    subcategories: [
      'Apotekstekniker',
      'Banktjänstemän',
      'Bensinstationspersonal',
      'Butikschef',
      'Butikssäljare, dagligvaror',
      'Butikssäljare, fackhandel',
      'Digital Marketing Specialist',
      'E-commerce Manager',
      'Evenemangs- och reseproducenter m.fl.',
      'Eventsäljare och butiksdemonistratörer m.fl.',
      'Fastighetsmäklare',
      'Företagssäljare',
      'Guider och resetedare',
      'Inköpare och upphandlare',
      'Inköps- och orderassistenter',
      'Kassapersonal m.fl.',
      'Kundtjänstpersonal',
      'Marknads- och försäljningsassistenter',
      'Marknadsanalytiker och marknadsförare m.fl.',
      'Marknadsundersökare och intervjuare',
      'Optikerassistenter',
      'Ordersamordnare m.fl.',
      'Resesäljare och trafikassistenter m.fl.',
      'SEO Specialist',
      'Social Media Manager',
      'Speditörer och transportmäklare',
      'Säljande butikschefer och avdelningschefer i butik',
      'Telefonförsäljare m.fl.',
      'Torg- och marknadsförsäljare m.fl.',
      'Uthyrare',
      'Visual Merchandiser',
      'Övriga förmedlare'
    ]
  },
  { 
    value: 'crafts', 
    label: 'Hantverkyrken', 
    keywords: ['hantverk', 'smed', 'keramiker', 'snickare', 'träarbete', 'metallarbete', 'bagare', 'konditor'],
    subcategories: [
      'Bagare och konditorer',
      'Fin-, inrednings- och möbelsnickare',
      'Finmekaniker',
      'Glastekniker',
      'Guld- och silversmeder',
      'Läderhantverkare och skomakare',
      'Manuella ytbehandlare, trä',
      'Musikinstrumentmakare och övriga konsthantverkare',
      'Skräddare och ateljésömmerskor m.fl.',
      'Smeder',
      'Sömmare',
      'Tapetserare'
    ]
  },
  { 
    value: 'restaurant', 
    label: 'Hotell, Restaurang, Storhushåll', 
    keywords: ['kock', 'servitör', 'hotell', 'restaurang', 'storhushåll', 'bagare', 'konditor', 'hovmästare', 'barista', 'catering'],
    subcategories: [
      'Barista',
      'Bartenders',
      'Cateringpersonal',
      'Croupierer och oddssättare m.fl.',
      'Hotellreceptionister m.fl.',
      'Hovmästare och servitörer',
      'Kafé- och konditorbiträden',
      'Kockar och kallskänkor',
      'Köksmästare och souschefer',
      'Pizzabagare m.fl.',
      'Restaurang- och köksbiträden m.fl.',
      'Storhushållsföreståndare'
    ]
  },
  { 
    value: 'healthcare', 
    label: 'Hälso- och Sjukvård', 
    keywords: ['sjuksköterska', 'läkare', 'vård', 'omsorg', 'tandläkare', 'fysioterapeut', 'undersköterska', 'vårdbiträde', 'nutrition', 'kostrådgivare', 'personal trainer', 'life coach'],
    subcategories: [
      'AT-läkare',
      'Ambulanssjuksköterskor m.fl.',
      'Ambulanssjukvårdare',
      'Anestesisjuksköterskor',
      'Apotekare',
      'Arbetsterapeuter',
      'Audionomer och logopeder',
      'Barnmorskor',
      'Barnsjuksköterskor',
      'Barnsköterskor',
      'Biomedicinska analytiker m.fl.',
      'Dietister',
      'Distriktssköterskor',
      'Djursjuksköterskor m.fl.',
      'Fysioterapeuter och sjukgymnaster',
      'Företagssköterskor',
      'Geriatriksjuksköterskor',
      'Grundutbildade sjuksköterskor',
      'Hemtjänstpersonal',
      'Intensivvårdssjuksköterskor',
      'Kiropraktorer och naprapater m.fl.',
      'Kostrådgivare',
      'Life Coach',
      'Nutritionist',
      'Operationssjuksköterskor',
      'Optiker',
      'Personal Trainer',
      'Psykiatrisjuksköterskor',
      'Psykologer',
      'Psykoterapeuter',
      'Receptarier',
      'Röntgensjuksköterskor',
      'ST-läkare',
      'Skolsköterskor',
      'Skötare',
      'Specialistläkare',
      'Tandhygienister',
      'Tandläkare',
      'Tandsköterskor',
      'Terapeuter inom alternativmedicin',
      'Undersköterskor, hemsjukvård, äldreboende och habilitering',
      'Undersköterskor, vård- och specialavdelning och mottagning',
      'Veterinärer',
      'Vårdbiträden',
      'Övrig vård- och omsorgspersonal',
      'Övriga läkare',
      'Övriga specialister inom hälso- och sjukvård',
      'Övriga specialistsjuksköterskor'
    ]
  },
  { 
    value: 'industry', 
    label: 'Industriell Tillverkning', 
    keywords: ['industri', 'tillverkning', 'produktion', 'maskinoperatör', 'kvalitet', 'process', 'tekniker'],
    subcategories: [
      'Arbetsledare inom tillverkning',
      'Bergsprängare',
      'Bobindare m.fl.',
      'Fordonsmontörer',
      'Gjutare',
      'Handpaketerare och andra fabriksarbetare',
      'Lackerare och industrimålare',
      'Maskinoperatörer inom ytbehandling, trä',
      'Maskinoperatörer, blekning, färgning och tvättning',
      'Maskinoperatörer, cement-, sten- och betongvaror',
      'Maskinoperatörer, farmaceutiska produkter',
      'Maskinoperatörer, gummiindustri',
      'Maskinoperatörer, kemisktekniska och fotografiska produkter',
      'Maskinoperatörer, kvarn-, bageri- och konfektyrindustri',
      'Maskinoperatörer, kött- och fiskberedningsindustri',
      'Maskinoperatörer, mejeri',
      'Maskinoperatörer, plastindustri',
      'Maskinoperatörer, pappersvaruindustri',
      'Maskinoperatörer, pappersindustri',
      'Maskinoperatörer, påfyllning, packning och märkning',
      'Maskinoperatörer, ytbehandling, trä',
      'Maskinställare och maskinoperatörer, metallarbete',
      'Maskinsnickare och maskinoperatörer, träindustri',
      'Montörer, elektrisk och elektronisk utrustning',
      'Montörer, metall-, gummi- och plastprodukter',
      'Montörer, träprodukter',
      'Operatörer inom sågverk, hyvleri och plywood m.m.',
      'Prepress tekniker',
      'Processoperatörer, papper',
      'Processoperatörer, pappersmassa',
      'Processoperatörer, stenkross- och malmförädling',
      'Provsmakare och kvalitetsbedömare',
      'Slaktare och styckare m.fl.',
      'Slipare m.fl.',
      'Stenhuggare m.fl.',
      'Stålkonstruktionsmontörer och grovplåtslagare',
      'Svetsare och gasskärare',
      'Tryckare',
      'Tunnplåtslagare',
      'Valsverksoperatörer',
      'Verktygsmakare',
      'Övriga maskin- och processoperatörer vid stål- och metallverk',
      'Övriga maskinoperatörer, livsmedelsindustri m.m.',
      'Övriga maskinoperatörer, textil-, skinn- och läderindustri',
      'Övriga montörer',
      'Övriga process- och maskinoperatörer'
    ]
  },
  { 
    value: 'installation', 
    label: 'Installation, Drift, Underhåll', 
    keywords: ['installation', 'drift', 'underhåll', 'reparatör', 'tekniker', 'service', 'elektriker', 'fastighet'],
    subcategories: [
      'Distributionselektriker',
      'Drifttekniker vid värme- och vattenverk',
      'Elektronikreparatörer och kommunikationselektriker m.fl.',
      'Fastighetsskötare',
      'Flygmekaniker m.fl.',
      'Industrielektriker',
      'Installations- och serviceelektriker',
      'Motorfordonsmekaniker och fordonsreparatörer',
      'Processövervakare, kemisk industri',
      'Processövervakare, metallproduktion',
      'Underhållsmekaniker och maskinreparatörer',
      'Vaktmästare m.fl.',
      'Övriga drifttekniker och processövervakare',
      'Övriga servicearbetare'
    ]
  },
  { 
    value: 'logistics', 
    label: 'Transport', 
    keywords: ['lager', 'logistik', 'transport', 'distribution', 'chaufför', 'lastbil', 'gaffeltruck', 'leverans', 'kurir', 'bud', 'uber', 'drönare', 'drone'],
    subcategories: [
      'Arbetsledare inom lager och terminal',
      'Bangårdspersonal', 
      'Brevbärare och postterminalarbetare',
      'Budbilsförare',
      'Buss- och spårvagnsförare',
      'Distributionschaufför',
      'Drone Pilot',
      'Fartygsbefäl m.fl.',
      'Flygledare',
      'Hamnarbetare',
      'Kabinpersonal m.fl.',
      'Kurir',
      'Lager- och terminalpersonal', 
      'Lastbilsförare m.fl.',
      'Lokförare',
      'Maskinbefäl',
      'Matroser och jungman m.fl.',
      'Piloter m.fl.',
      'Ramppersonal, flyttkarlar och varupåfyllare m.fl.',
      'Reklamutdelare och tidningsdistributörer',
      'Taxiförare m.fl.',
      'Transportledare och transportsamordnare',
      'Truckförare',
      'Tågvärdar och ombordansvariga m.fl.',
      'Uber-förare'
    ]
  },
  { 
    value: 'beauty', 
    label: 'Kropps- och Skönhetsvård', 
    keywords: ['frisör', 'skönhet', 'massage', 'naglar', 'kosmetolog', 'fotvård', 'hudterapeut', 'makeup', 'tatuering'],
    subcategories: [
      'Fotterapeuter',
      'Frisörer',
      'Hudterapeuter',
      'Makeup Artist',
      'Massörer och massageterapeuter',
      'Tatuerare',
      'Övriga skönhets- och kroppsterapeuter'
    ]
  },
  { 
    value: 'creative', 
    label: 'Kultur, Media, Design', 
    keywords: ['design', 'grafisk', 'kreativ', 'media', 'journalist', 'fotograf', 'video', 'kultur', 'konstnär', 'bibliotek', 'content', 'influencer', 'podcast', 'streaming', 'esport', 'gaming'],
    subcategories: [
      'Bibliotekarier och arkivarier',
      'Bild- och sandningstekniker',
      'Bildkonstnärer m.fl.',
      'Content Creator',
      'Designer inom spel och digitala medier',
      'E-sports spelare',
      'Fotografer',
      'Författare m.fl.',
      'Grafiska formgivare m.fl.',
      'Industridesigner',
      'Influencer',
      'Inredare, dekoratörer och scenografer m.fl.',
      'Inspicienter och scriptör m.fl.',
      'Journalister m.fl.',
      'Koreografer och dansare',
      'Ljus-, ljud- och scentekniker',
      'Museiintendenter m.fl.',
      'Musiker, sångare och kompositörer',
      'Podcaster',
      'Regissörer och producenter av film, teater m.m.',
      'Skådespelare',
      'Streamer',
      'Översättare, tolkar och lingvister m.fl.',
      'Övriga designer och formgivare',
      'Övriga yrken inom kultur och underhållning'
    ]
  },
  { 
    value: 'military', 
    label: 'Militärt Arbete', 
    keywords: ['militär', 'försvar', 'soldat', 'officer', 'specialistofficerare'],
    subcategories: [
      'Officerare',
      'Soldater m.fl.',
      'Specialistofficerare'
    ]
  },
  { 
    value: 'agriculture', 
    label: 'Naturbruk', 
    keywords: ['lantbruk', 'jordbruk', 'skog', 'djur', 'trädgård', 'fiske', 'skogsarbete', 'hundvakt', 'djurpassning'],
    subcategories: [
      'Bärplockare och plantörer m.fl.',
      'Djurpassare',
      'Fiskare',
      'Fiskodlare',
      'Förare av jordbruks- och skogsmaskiner',
      'Hundvakt',
      'Odlare av jordbruksväxter, frukt och bär',
      'Skogsarbetare',
      'Specialister och rådgivare inom lantbruk m.m.',
      'Specialister och rådgivare inom skogsbruk',
      'Trädgårdsanläggare m.fl.',
      'Trädgårdsodlare',
      'Uppfödare och skötare av lantbrukets husdjur',
      'Uppfödare och skötare av sällskapsdjur',
      'Växtodlare och djuruppfödare, blandad drift',
      'Övriga djuruppfödare och djurskötare'
    ]
  },
  { 
    value: 'science', 
    label: 'Naturvetenskapligt Arbete', 
    keywords: ['forskning', 'vetenskap', 'laboratorium', 'kemi', 'biologi', 'fysik', 'matematik'],
    subcategories: [
      'Cell- och molekylärbiologer m.fl.',
      'Farmakologer och biomedicinare',
      'Fysiker och astronomer',
      'Geologer och geofysiker m.fl.',
      'Kemister',
      'Matematiker och aktuarier',
      'Meteorologer',
      'Miljö- och hälsoskyddsinspektörer',
      'Specialister inom miljöskydd och miljöteknik',
      'Växt- och djurbiologer'
    ]
  },
  { 
    value: 'education', 
    label: 'Pedagogiskt Arbete', 
    keywords: ['lärare', 'utbildning', 'skola', 'universitet', 'förskola', 'pedagog', 'barnskötare', 'fritidsledare'],
    subcategories: [
      'Doktorander',
      'Elevassistenter m.fl.',
      'Forskarassistenter m.fl.',
      'Fritidspedagoger',
      'Förskollärare',
      'Grundskollärare',
      'Gymnasielärare',
      'Idrottsstränare och instruktörer m.fl.',
      'Lärare i yrkesämnen',
      'Professionella idrottutövare',
      'Professorer',
      'Speciallärare och specialpedagoger m.fl.',
      'Studie- och yrkesvägledare',
      'Trafiklarare',
      'Universitets- och högskolelektorer',
      'Övriga pedagoger med teoretisk specialistkompetens',
      'Övriga universitets- och högskolelärare',
      'Övriga utbildare och instruktörer'
    ]
  },
  { 
    value: 'cleaning', 
    label: 'Sanering och Renhållning', 
    keywords: ['städ', 'rengöring', 'sanering', 'renhållning', 'lokalvård', 'skorstensfejare', 'hemstäd'],
    subcategories: [
      'Bilrekonditionerare, fönsterputsare m.fl.',
      'Hemstädare',
      'Renhållnings- och återvinningsarbetare',
      'Renhållningschaufför',
      'Saneringsarbetare m.fl.',
      'Skorstensfjejare',
      'Städare',
      'Städledare och husfruar',
      'Övrig hemservicepersonal m.fl.'
    ]
  },
  { 
    value: 'security', 
    label: 'Säkerhet och Skydd', 
    keywords: ['säkerhet', 'vakt', 'väktare', 'brandman', 'skydd', 'bevakning'],
    subcategories: [
      'Brandmän',
      'Säkerhetsvakt',
      'Väktare',
      'Övrig säkerhetspersonal'
    ]
  },
  { 
    value: 'social',
    label: 'Socialt Arbete', 
    keywords: ['social', 'socialtjänst', 'stöd', 'hjälp', 'omsorg', 'kurator', 'behandling'],
    subcategories: [
      'Barnskötare',
      'Begravnings- och krematoriepersonal',
      'Behandlingsassistenter och socialpedagoger m.fl.',
      'Biståndshandläggare m.fl.',
      'Diakoner',
      'Friskvårdskonsulenter och hälsopedagoger m.fl.',
      'Fritidsledare m.fl.',
      'Kuratorer',
      'Pastorer m.fl.',
      'Personliga assistenter',
      'Präster',
      'Socialsekreterare',
      'Vårdare, boendestödjare',
      'Övrig servicepersonal',
      'Övriga yrken inom socialt arbete'
    ]
  },
  { 
    value: 'security', 
    label: 'Säkerhetsarbete', 
    keywords: ['säkerhet', 'vakt', 'polis', 'brandman', 'ordning', 'bevakning'],
    subcategories: [
      'Arbetsmiljöingenjörer, yrkes- och miljöhygieniker',
      'Brandingenjörer och byggnadsinspektörer m.fl.',
      'Brandmän',
      'Kriminalvårdare',
      'Poliser',
      'SOS-operatörer m.fl.',
      'Säkerhetsinspektörer m.fl.',
      'Tull- och kustbevakningtjänstemän',
      'Väktare och ordningsvakter',
      'Övrig bevaknings- och säkerhetspersonal'
    ]
  },
  { 
    value: 'technical', 
    label: 'Tekniskt Arbete', 
    keywords: ['ingenjör', 'tekniker', 'konstruktör', 'design', 'utveckling', 'arkitekt', 'civilingenjör'],
    subcategories: [
      'Arkitekter m.fl.',
      'Civilingenjörsyrken inom elektroteknik',
      'Civilingenjörsyrken inom gruvteknik och metallurgi',
      'Civilingenjörsyrken inom kemi och kemiteknik',
      'Civilingenjörsyrken inom logistik och produktionsplanering',
      'Civilingenjörsyrken inom maskinteknik',
      'Fastighetsförvaltare',
      'Flygtekniker',
      'GIS- och kartingenjörer',
      'Ingenjörer och tekniker inom elektroteknik',
      'Ingenjörer och tekniker inom gruvteknik och metallurgi',
      'Ingenjörer och tekniker inom industri, logistik och produktionsplanering',
      'Ingenjörer och tekniker inom kemi och kemiteknik',
      'Ingenjörer och tekniker inom maskinteknik',
      'Laboratorieingenjörer',
      'Landskapsarkitekter',
      'Lantmätare',
      'Planeringsarkitekter m.fl.',
      'Tandtekniker och ortopedingenjörer m.fl.',
      'Tekniker, bilddiagnostik och medicinteknisk utrustning',
      'Övriga civilingenjörsyrken',
      'Övriga ingenjörer och tekniker'
    ]
  }
];

// Get all occupations as a flat list for search functionality
export const getAllOccupations = (): string[] => {
  const allOccupations: string[] = [];
  OCCUPATION_CATEGORIES.forEach(category => {
    allOccupations.push(...category.subcategories);
  });
  return allOccupations.sort();
};

// Search occupations by term
export const searchOccupations = (searchTerm: string): string[] => {
  if (!searchTerm || searchTerm.length < 2) {
    return [];
  }
  
  const term = searchTerm.toLowerCase();
  const allOccupations = getAllOccupations();
  
  return allOccupations.filter(occupation => 
    occupation.toLowerCase().includes(term)
  ).slice(0, 10); // Limit to 10 results
};