/**
 * useCandidateSummary — encapsulates AI summary fetch, generation, and polling.
 *
 * Features:
 * - 3-layer caching (memory → localStorage → DB)
 * - Auto-generation when no summary exists
 * - Exponential backoff polling for async CV analysis
 * - Graceful fallbacks for missing / invalid CVs
 */
import { useState, useCallback, useEffect, useRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { useAuth } from '@/hooks/useAuth';
import {
  summaryCache,
  getPersistedCacheValue,
  setPersistedCacheValue,
  SUMMARY_STORAGE_KEY,
} from '@/components/candidateProfile/candidateProfileCache';
import type { CandidateSummaryCacheValue } from '@/components/candidateProfile/candidateProfileCache';

interface UseCandidateSummaryOptions {
  applicantId: string | null;
  jobId: string | null;
  applicationId: string | null;
  cvUrl: string | null;
  open: boolean;
}

// ─── Pure helpers ────────────────────────────────────────────────────
function extractSummaryMeta(keyPoints: any[] | null | undefined) {
  const docPoint = (keyPoints || []).find(
    (p: any) => typeof p?.text === 'string' && p.text.startsWith('Dokumenttyp:')
  );
  const documentType = typeof docPoint?.text === 'string'
    ? docPoint.text.replace('Dokumenttyp:', '').trim()
    : null;
  const isValidCv = documentType ? documentType.toLowerCase() === 'cv' : undefined;
  const sourceCvUrl = docPoint?.meta?.source_cv_url as string | undefined;
  return { documentType, isValidCv, sourceCvUrl };
}

function buildCacheKey(applicantId: string, jobId: string | null, cvUrl: string | null) {
  return `${applicantId}_${jobId || 'no-job'}_${cvUrl || '__no-cv__'}`;
}

export function useCandidateSummary({ applicantId, jobId, applicationId, cvUrl, open }: UseCandidateSummaryOptions) {
  const { user } = useAuth();

  // Initialize state from cache synchronously to avoid flicker on reopen
  const getInitialSummary = (): CandidateSummaryCacheValue | null => {
    if (!applicantId) return null;
    const cacheKey = buildCacheKey(applicantId, jobId, cvUrl);
    const memCached = summaryCache.get(cacheKey);
    if (memCached) return memCached;
    const persisted = getPersistedCacheValue<CandidateSummaryCacheValue>(SUMMARY_STORAGE_KEY, cacheKey);
    if (persisted) {
      summaryCache.set(cacheKey, persisted);
      return persisted;
    }
    return null;
  };

  const [aiSummary, setAiSummary] = useState<CandidateSummaryCacheValue | null>(getInitialSummary);
  const [loadingSummary, setLoadingSummary] = useState(false);
  const [generatingSummary, setGeneratingSummary] = useState(false);
  const autoGeneratedKeysRef = useRef(new Set<string>());
  const lastApplicantKeyRef = useRef<string>('');

  // ─── Fetch existing summary ─────────────────────────────────────
  const fetchAiSummary = useCallback(async (): Promise<{ shouldAutoGenerate: boolean }> => {
    if (!applicantId) return { shouldAutoGenerate: false };

    const cacheKey = buildCacheKey(applicantId, jobId, cvUrl);

    // Check in-memory cache
    const cached = summaryCache.get(cacheKey);
    if (cached) { setAiSummary(cached); return { shouldAutoGenerate: false }; }

    // Check localStorage cache
    const persisted = getPersistedCacheValue<CandidateSummaryCacheValue>(SUMMARY_STORAGE_KEY, cacheKey);
    if (persisted) {
      summaryCache.set(cacheKey, persisted);
      setAiSummary(persisted);
      return { shouldAutoGenerate: false };
    }

    // No CV → stable fallback
    if (!cvUrl) {
      const noCvSummary: CandidateSummaryCacheValue = {
        summary_text: 'Kandidaten har inte laddat upp något CV',
        key_points: null,
        document_type: null,
        is_valid_cv: false,
      };
      summaryCache.set(cacheKey, noCvSummary);
      setPersistedCacheValue(SUMMARY_STORAGE_KEY, cacheKey, noCvSummary);
      setAiSummary(noCvSummary);
      return { shouldAutoGenerate: false };
    }

    setLoadingSummary(true);

    try {
      let data: { summary_text: string; key_points: any[] | null } | null = null;

      // Try job-specific summary first
      if (jobId) {
        const { data: jobSummary, error } = await supabase
          .from('candidate_summaries')
          .select('summary_text, key_points')
          .eq('job_id', jobId)
          .eq('applicant_id', applicantId)
          .order('generated_at', { ascending: false })
          .limit(1)
          .maybeSingle();

        if (error) throw error;
        if (jobSummary) {
          data = {
            summary_text: jobSummary.summary_text,
            key_points: (jobSummary.key_points as any[] | null) || null,
          };
        }
      }

      // Fallback to proactive profile summary
      if (!data) {
        const { data: profileSummary, error: profileError } = await supabase
          .from('profile_cv_summaries')
          .select('summary_text, key_points, is_valid_cv, document_type, cv_url')
          .eq('user_id', applicantId)
          .maybeSingle();

        if (!profileError && profileSummary) {
          if (!cvUrl || profileSummary.cv_url === cvUrl) {
            const summaryData: CandidateSummaryCacheValue = {
              summary_text: profileSummary.summary_text || '',
              key_points: (profileSummary.key_points as any[] | null) || [],
              document_type: profileSummary.document_type,
              is_valid_cv: profileSummary.is_valid_cv,
            };
            summaryCache.set(cacheKey, summaryData);
            setPersistedCacheValue(SUMMARY_STORAGE_KEY, cacheKey, summaryData);
            setAiSummary(summaryData);
            return { shouldAutoGenerate: false };
          }
        }
      }

      if (!data) {
        setAiSummary(null);
        return { shouldAutoGenerate: true };
      }

      const keyPoints = (data.key_points as any[] | null) || null;
      const meta = extractSummaryMeta(keyPoints);

      // Check if summary is stale (CV changed since summary was generated).
      // Only treat as stale when source_cv_url exists AND differs.
      // Older summaries without source_cv_url should still be considered valid.
      const isStale = !!cvUrl && !!meta.sourceCvUrl && meta.sourceCvUrl !== cvUrl;
      if (isStale) {
        setAiSummary(null);
        return { shouldAutoGenerate: true };
      }

      let isValidCv = meta.isValidCv;
      let documentType = meta.documentType;

      if (typeof isValidCv !== 'boolean') {
        isValidCv = !data.summary_text.includes('Kan inte läsa av ett CV');
      }
      if (!documentType && data.summary_text.includes('Kan inte läsa av ett CV')) {
        const match = data.summary_text.match(/dokumentet är (.+?)\./);
        if (match) documentType = match[1];
      }

      const summaryResult: CandidateSummaryCacheValue = {
        summary_text: data.summary_text,
        key_points: keyPoints as any,
        document_type: documentType,
        is_valid_cv: isValidCv,
      };
      summaryCache.set(cacheKey, summaryResult);
      setPersistedCacheValue(SUMMARY_STORAGE_KEY, cacheKey, summaryResult);
      setAiSummary(summaryResult);

      return { shouldAutoGenerate: false };
    } catch (error) {
      console.error('Error fetching AI summary:', error);
      return { shouldAutoGenerate: false };
    } finally {
      setLoadingSummary(false);
    }
  }, [applicantId, jobId, cvUrl]);

  // ─── Generate summary via edge function ─────────────────────────
  const generateAiSummary = useCallback(async (silent = false) => {
    if (!applicantId) return;
    if (!navigator.onLine) {
      if (!silent) toast.error('Du måste vara online för att generera sammanfattning');
      return;
    }

    setGeneratingSummary(true);

    try {
      const { data, error } = await supabase.functions.invoke('generate-cv-summary', {
        body: {
          applicant_id: applicantId,
          application_id: applicationId,
          job_id: jobId,
          cv_url_override: cvUrl,
        },
      });

      if (error) throw error;
      if (data?.error) {
        if (!silent) toast.error(data.error);
        return;
      }

      if (!silent) {
        if (data?.is_valid_cv === false) {
          toast.message('Dokumentet är inte ett CV');
        } else {
          toast.success('Sammanfattning genererad från CV');
        }
      }

      if (data?.summary) {
        const cacheKey = buildCacheKey(applicantId, jobId, cvUrl);
        const genResult: CandidateSummaryCacheValue = {
          summary_text: data.summary.summary_text,
          key_points: data.summary.key_points,
          document_type: data.document_type || data.summary.document_type || null,
          is_valid_cv: data.is_valid_cv,
        };
        summaryCache.set(cacheKey, genResult);
        setPersistedCacheValue(SUMMARY_STORAGE_KEY, cacheKey, genResult);
        setAiSummary(genResult);
      }
    } catch (error) {
      console.error('Error generating CV summary:', error);
      if (!silent) toast.error('Kunde inte generera sammanfattning');
    } finally {
      setGeneratingSummary(false);
    }
  }, [applicantId, applicationId, jobId, cvUrl]);

  // ─── Sync state when candidate/job changes or dialog opens ─────
  useEffect(() => {
    if (!applicantId || !user) return;

    const cacheKey = buildCacheKey(applicantId, jobId, cvUrl);

    // If candidate changed, immediately restore from cache (no flicker)
    if (lastApplicantKeyRef.current !== cacheKey) {
      lastApplicantKeyRef.current = cacheKey;
      setLoadingSummary(false);
      setGeneratingSummary(false);

      const cached = summaryCache.get(cacheKey)
        || getPersistedCacheValue<CandidateSummaryCacheValue>(SUMMARY_STORAGE_KEY, cacheKey);
      if (cached) {
        summaryCache.set(cacheKey, cached);
        setAiSummary(cached);
        return; // Already have it, no fetch needed
      }
      setAiSummary(null);
    }

    if (!open) return;

    // Only fetch from DB if not already cached
    if (aiSummary) return;

    (async () => {
      const result = await fetchAiSummary();
      if (result?.shouldAutoGenerate && cvUrl && !autoGeneratedKeysRef.current.has(cacheKey)) {
        autoGeneratedKeysRef.current.add(cacheKey);
        generateAiSummary(true);
      }
    })();
  }, [open, applicantId, jobId, cvUrl, user?.id]); // eslint-disable-line react-hooks/exhaustive-deps

  // ─── Polling with exponential backoff ──────────────────────────
  useEffect(() => {
    if (!open || !applicantId || aiSummary || loadingSummary || generatingSummary || !cvUrl) return;

    let attempt = 0;
    const MAX_ATTEMPTS = 10;
    let timeoutId: ReturnType<typeof setTimeout>;

    const poll = async () => {
      if (!navigator.onLine || attempt >= MAX_ATTEMPTS) return;
      attempt++;

      try {
        const { data } = await supabase
          .from('candidate_summaries')
          .select('summary_text, key_points')
          .eq('job_id', jobId!)
          .eq('applicant_id', applicantId)
          .order('generated_at', { ascending: false })
          .limit(1)
          .maybeSingle();

        if (data) {
          await fetchAiSummary();
          return; // Stop polling
        }
      } catch (error) {
        console.error('Polling error:', error);
      }

      const delay = 3000 * Math.pow(2, attempt - 1);
      timeoutId = setTimeout(poll, delay);
    };

    timeoutId = setTimeout(poll, 3000);
    return () => clearTimeout(timeoutId);
  }, [open, applicantId, aiSummary, loadingSummary, generatingSummary, cvUrl, jobId, fetchAiSummary]);

  // ─── Reset — only clears transient state, cache handles data ────
  const reset = useCallback(() => {
    // Don't clear aiSummary — the useEffect above will restore from cache
    // when applicantId/jobId/cvUrl change. This prevents flicker.
    setLoadingSummary(false);
    setGeneratingSummary(false);
  }, []);

  return {
    aiSummary,
    loadingSummary,
    generatingSummary,
    reset,
  };
}
