/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AiUsageRouteImport } from './routes/ai-usage'
import { Route as AnnonserRouteImport } from './routes/annonser'
import { Route as ArbetsgivareRouteImport } from './routes/arbetsgivare'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CompanyProfileRouteImport } from './routes/company-profile'
import { Route as ConfirmRouteImport } from './routes/confirm'
import { Route as CvTunnelRouteImport } from './routes/cv-tunnel'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DpaRouteImport } from './routes/dpa'
import { Route as EmailConfirmRouteImport } from './routes/email-confirm'
import { Route as EmailRedirectRouteImport } from './routes/email-redirect'
import { Route as EmployerProfileRouteImport } from './routes/employer-profile'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IntegritetspolicyRouteImport } from './routes/integritetspolicy'
import { Route as IntervjusvarRouteImport } from './routes/intervjusvar'
import { Route as JobbsokareRouteImport } from './routes/jobbsokare'
import { Route as KommunerRouteImport } from './routes/kommuner'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as MigrateMediaRouteImport } from './routes/migrate-media'
import { Route as MyApplicationsRouteImport } from './routes/my-applications'
import { Route as MyCandidatesRouteImport } from './routes/my-candidates'
import { Route as MyJobsRouteImport } from './routes/my-jobs'
import { Route as OmOssRouteImport } from './routes/om-oss'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProfilePreviewRouteImport } from './routes/profile-preview'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetRedirectRouteImport } from './routes/reset-redirect'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SavedJobsRouteImport } from './routes/saved-jobs'
import { Route as SearchJobsRouteImport } from './routes/search-jobs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TeamInviteRouteImport } from './routes/team-invite'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as ValjPlanRouteImport } from './routes/valj-plan'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as YrkenRouteImport } from './routes/yrken'
import { Route as AnnonsJobIdRouteImport } from './routes/annons.$jobId'
import { Route as GuiderIndexRouteImport } from './routes/guider.index'
import { Route as GuiderSlugRouteImport } from './routes/guider.$slug'
import { Route as GuiderCvMall2026RouteImport } from './routes/guider.cv-mall-2026'
import { Route as JobApplicationJobIdRouteImport } from './routes/job-application.$jobId'
import { Route as JobDetailsJobIdRouteImport } from './routes/job-details.$jobId'
import { Route as JobViewJobIdRouteImport } from './routes/job-view.$jobId'
import { Route as JobJobIdRouteImport } from './routes/job.$jobId'
import { Route as JobbIndexRouteImport } from './routes/jobb.index'
import { Route as KommunKommunSlugRouteImport } from './routes/kommun.$kommunSlug'
import { Route as YrkeOccupationSlugRouteImport } from './routes/yrke.$occupationSlug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as JobbCitySlugIndexRouteImport } from './routes/jobb.$citySlug.index'
import { Route as JobbCitySlugOccupationSlugRouteImport } from './routes/jobb.$citySlug.$occupationSlug'
import { Route as OauthConnectorReturnRouteImport } from './routes/oauth.$connector.return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AiUsageRoute = AiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnonserRoute = AnnonserRouteImport.update({
  id: '/annonser',
  path: '/annonser',
  getParentRoute: () => rootRouteImport,
} as any)
const ArbetsgivareRoute = ArbetsgivareRouteImport.update({
  id: '/arbetsgivare',
  path: '/arbetsgivare',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyProfileRoute = CompanyProfileRouteImport.update({
  id: '/company-profile',
  path: '/company-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmRoute = ConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const CvTunnelRoute = CvTunnelRouteImport.update({
  id: '/cv-tunnel',
  path: '/cv-tunnel',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DpaRoute = DpaRouteImport.update({
  id: '/dpa',
  path: '/dpa',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailConfirmRoute = EmailConfirmRouteImport.update({
  id: '/email-confirm',
  path: '/email-confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRedirectRoute = EmailRedirectRouteImport.update({
  id: '/email-redirect',
  path: '/email-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerProfileRoute = EmployerProfileRouteImport.update({
  id: '/employer-profile',
  path: '/employer-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegritetspolicyRoute = IntegritetspolicyRouteImport.update({
  id: '/integritetspolicy',
  path: '/integritetspolicy',
  getParentRoute: () => rootRouteImport,
} as any)
const IntervjusvarRoute = IntervjusvarRouteImport.update({
  id: '/intervjusvar',
  path: '/intervjusvar',
  getParentRoute: () => rootRouteImport,
} as any)
const JobbsokareRoute = JobbsokareRouteImport.update({
  id: '/jobbsokare',
  path: '/jobbsokare',
  getParentRoute: () => rootRouteImport,
} as any)
const KommunerRoute = KommunerRouteImport.update({
  id: '/kommuner',
  path: '/kommuner',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrateMediaRoute = MigrateMediaRouteImport.update({
  id: '/migrate-media',
  path: '/migrate-media',
  getParentRoute: () => rootRouteImport,
} as any)
const MyApplicationsRoute = MyApplicationsRouteImport.update({
  id: '/my-applications',
  path: '/my-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCandidatesRoute = MyCandidatesRouteImport.update({
  id: '/my-candidates',
  path: '/my-candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const MyJobsRoute = MyJobsRouteImport.update({
  id: '/my-jobs',
  path: '/my-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const OmOssRoute = OmOssRouteImport.update({
  id: '/om-oss',
  path: '/om-oss',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePreviewRoute = ProfilePreviewRouteImport.update({
  id: '/profile-preview',
  path: '/profile-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetRedirectRoute = ResetRedirectRouteImport.update({
  id: '/reset-redirect',
  path: '/reset-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedJobsRoute = SavedJobsRouteImport.update({
  id: '/saved-jobs',
  path: '/saved-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchJobsRoute = SearchJobsRouteImport.update({
  id: '/search-jobs',
  path: '/search-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamInviteRoute = TeamInviteRouteImport.update({
  id: '/team-invite',
  path: '/team-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ValjPlanRoute = ValjPlanRouteImport.update({
  id: '/valj-plan',
  path: '/valj-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const YrkenRoute = YrkenRouteImport.update({
  id: '/yrken',
  path: '/yrken',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnonsJobIdRoute = AnnonsJobIdRouteImport.update({
  id: '/annons/$jobId',
  path: '/annons/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderIndexRoute = GuiderIndexRouteImport.update({
  id: '/guider/',
  path: '/guider/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderSlugRoute = GuiderSlugRouteImport.update({
  id: '/guider/$slug',
  path: '/guider/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiderCvMall2026Route = GuiderCvMall2026RouteImport.update({
  id: '/guider/cv-mall-2026',
  path: '/guider/cv-mall-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const JobApplicationJobIdRoute = JobApplicationJobIdRouteImport.update({
  id: '/job-application/$jobId',
  path: '/job-application/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobDetailsJobIdRoute = JobDetailsJobIdRouteImport.update({
  id: '/job-details/$jobId',
  path: '/job-details/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobViewJobIdRoute = JobViewJobIdRouteImport.update({
  id: '/job-view/$jobId',
  path: '/job-view/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobJobIdRoute = JobJobIdRouteImport.update({
  id: '/job/$jobId',
  path: '/job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobbIndexRoute = JobbIndexRouteImport.update({
  id: '/jobb/',
  path: '/jobb/',
  getParentRoute: () => rootRouteImport,
} as any)
const KommunKommunSlugRoute = KommunKommunSlugRouteImport.update({
  id: '/kommun/$kommunSlug',
  path: '/kommun/$kommunSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const YrkeOccupationSlugRoute = YrkeOccupationSlugRouteImport.update({
  id: '/yrke/$occupationSlug',
  path: '/yrke/$occupationSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const JobbCitySlugIndexRoute = JobbCitySlugIndexRouteImport.update({
  id: '/jobb/$citySlug/',
  path: '/jobb/$citySlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobbCitySlugOccupationSlugRoute =
  JobbCitySlugOccupationSlugRouteImport.update({
    id: '/jobb/$citySlug/$occupationSlug',
    path: '/jobb/$citySlug/$occupationSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const OauthConnectorReturnRoute = OauthConnectorReturnRouteImport.update({
  id: '/oauth/$connector/return',
  path: '/oauth/$connector/return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-usage': typeof AiUsageRoute
  '/annonser': typeof AnnonserRoute
  '/arbetsgivare': typeof ArbetsgivareRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/candidates': typeof CandidatesRoute
  '/checkout': typeof CheckoutRoute
  '/company-profile': typeof CompanyProfileRoute
  '/confirm': typeof ConfirmRoute
  '/cv-tunnel': typeof CvTunnelRoute
  '/dashboard': typeof DashboardRoute
  '/dpa': typeof DpaRoute
  '/email-confirm': typeof EmailConfirmRoute
  '/email-redirect': typeof EmailRedirectRoute
  '/employer-profile': typeof EmployerProfileRoute
  '/home': typeof HomeRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/intervjusvar': typeof IntervjusvarRoute
  '/jobbsokare': typeof JobbsokareRoute
  '/kommuner': typeof KommunerRoute
  '/messages': typeof MessagesRoute
  '/migrate-media': typeof MigrateMediaRoute
  '/my-applications': typeof MyApplicationsRoute
  '/my-candidates': typeof MyCandidatesRoute
  '/my-jobs': typeof MyJobsRoute
  '/om-oss': typeof OmOssRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/profile-preview': typeof ProfilePreviewRoute
  '/reports': typeof ReportsRoute
  '/reset-redirect': typeof ResetRedirectRoute
  '/reviews': typeof ReviewsRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/search-jobs': typeof SearchJobsRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/team-invite': typeof TeamInviteRoute
  '/templates': typeof TemplatesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/valj-plan': typeof ValjPlanRoute
  '/verify': typeof VerifyRoute
  '/yrken': typeof YrkenRoute
  '/annons/$jobId': typeof AnnonsJobIdRoute
  '/guider/$slug': typeof GuiderSlugRoute
  '/guider/cv-mall-2026': typeof GuiderCvMall2026Route
  '/job-application/$jobId': typeof JobApplicationJobIdRoute
  '/job-details/$jobId': typeof JobDetailsJobIdRoute
  '/job-view/$jobId': typeof JobViewJobIdRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/kommun/$kommunSlug': typeof KommunKommunSlugRoute
  '/yrke/$occupationSlug': typeof YrkeOccupationSlugRoute
  '/guider/': typeof GuiderIndexRoute
  '/jobb/': typeof JobbIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/jobb/$citySlug/$occupationSlug': typeof JobbCitySlugOccupationSlugRoute
  '/oauth/$connector/return': typeof OauthConnectorReturnRoute
  '/jobb/$citySlug/': typeof JobbCitySlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-usage': typeof AiUsageRoute
  '/annonser': typeof AnnonserRoute
  '/arbetsgivare': typeof ArbetsgivareRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/candidates': typeof CandidatesRoute
  '/checkout': typeof CheckoutRoute
  '/company-profile': typeof CompanyProfileRoute
  '/confirm': typeof ConfirmRoute
  '/cv-tunnel': typeof CvTunnelRoute
  '/dashboard': typeof DashboardRoute
  '/dpa': typeof DpaRoute
  '/email-confirm': typeof EmailConfirmRoute
  '/email-redirect': typeof EmailRedirectRoute
  '/employer-profile': typeof EmployerProfileRoute
  '/home': typeof HomeRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/intervjusvar': typeof IntervjusvarRoute
  '/jobbsokare': typeof JobbsokareRoute
  '/kommuner': typeof KommunerRoute
  '/messages': typeof MessagesRoute
  '/migrate-media': typeof MigrateMediaRoute
  '/my-applications': typeof MyApplicationsRoute
  '/my-candidates': typeof MyCandidatesRoute
  '/my-jobs': typeof MyJobsRoute
  '/om-oss': typeof OmOssRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/profile-preview': typeof ProfilePreviewRoute
  '/reports': typeof ReportsRoute
  '/reset-redirect': typeof ResetRedirectRoute
  '/reviews': typeof ReviewsRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/search-jobs': typeof SearchJobsRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/team-invite': typeof TeamInviteRoute
  '/templates': typeof TemplatesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/valj-plan': typeof ValjPlanRoute
  '/verify': typeof VerifyRoute
  '/yrken': typeof YrkenRoute
  '/annons/$jobId': typeof AnnonsJobIdRoute
  '/guider/$slug': typeof GuiderSlugRoute
  '/guider/cv-mall-2026': typeof GuiderCvMall2026Route
  '/job-application/$jobId': typeof JobApplicationJobIdRoute
  '/job-details/$jobId': typeof JobDetailsJobIdRoute
  '/job-view/$jobId': typeof JobViewJobIdRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/kommun/$kommunSlug': typeof KommunKommunSlugRoute
  '/yrke/$occupationSlug': typeof YrkeOccupationSlugRoute
  '/guider': typeof GuiderIndexRoute
  '/jobb': typeof JobbIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/jobb/$citySlug/$occupationSlug': typeof JobbCitySlugOccupationSlugRoute
  '/oauth/$connector/return': typeof OauthConnectorReturnRoute
  '/jobb/$citySlug': typeof JobbCitySlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/ai-usage': typeof AiUsageRoute
  '/annonser': typeof AnnonserRoute
  '/arbetsgivare': typeof ArbetsgivareRoute
  '/auth': typeof AuthRoute
  '/billing': typeof BillingRoute
  '/candidates': typeof CandidatesRoute
  '/checkout': typeof CheckoutRoute
  '/company-profile': typeof CompanyProfileRoute
  '/confirm': typeof ConfirmRoute
  '/cv-tunnel': typeof CvTunnelRoute
  '/dashboard': typeof DashboardRoute
  '/dpa': typeof DpaRoute
  '/email-confirm': typeof EmailConfirmRoute
  '/email-redirect': typeof EmailRedirectRoute
  '/employer-profile': typeof EmployerProfileRoute
  '/home': typeof HomeRoute
  '/integritetspolicy': typeof IntegritetspolicyRoute
  '/intervjusvar': typeof IntervjusvarRoute
  '/jobbsokare': typeof JobbsokareRoute
  '/kommuner': typeof KommunerRoute
  '/messages': typeof MessagesRoute
  '/migrate-media': typeof MigrateMediaRoute
  '/my-applications': typeof MyApplicationsRoute
  '/my-candidates': typeof MyCandidatesRoute
  '/my-jobs': typeof MyJobsRoute
  '/om-oss': typeof OmOssRoute
  '/payment': typeof PaymentRoute
  '/profile': typeof ProfileRoute
  '/profile-preview': typeof ProfilePreviewRoute
  '/reports': typeof ReportsRoute
  '/reset-redirect': typeof ResetRedirectRoute
  '/reviews': typeof ReviewsRoute
  '/saved-jobs': typeof SavedJobsRoute
  '/search-jobs': typeof SearchJobsRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/subscription': typeof SubscriptionRoute
  '/support': typeof SupportRoute
  '/team-invite': typeof TeamInviteRoute
  '/templates': typeof TemplatesRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/valj-plan': typeof ValjPlanRoute
  '/verify': typeof VerifyRoute
  '/yrken': typeof YrkenRoute
  '/annons/$jobId': typeof AnnonsJobIdRoute
  '/guider/$slug': typeof GuiderSlugRoute
  '/guider/cv-mall-2026': typeof GuiderCvMall2026Route
  '/job-application/$jobId': typeof JobApplicationJobIdRoute
  '/job-details/$jobId': typeof JobDetailsJobIdRoute
  '/job-view/$jobId': typeof JobViewJobIdRoute
  '/job/$jobId': typeof JobJobIdRoute
  '/kommun/$kommunSlug': typeof KommunKommunSlugRoute
  '/yrke/$occupationSlug': typeof YrkeOccupationSlugRoute
  '/guider/': typeof GuiderIndexRoute
  '/jobb/': typeof JobbIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/jobb/$citySlug/$occupationSlug': typeof JobbCitySlugOccupationSlugRoute
  '/oauth/$connector/return': typeof OauthConnectorReturnRoute
  '/jobb/$citySlug/': typeof JobbCitySlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/ai-usage'
    | '/annonser'
    | '/arbetsgivare'
    | '/auth'
    | '/billing'
    | '/candidates'
    | '/checkout'
    | '/company-profile'
    | '/confirm'
    | '/cv-tunnel'
    | '/dashboard'
    | '/dpa'
    | '/email-confirm'
    | '/email-redirect'
    | '/employer-profile'
    | '/home'
    | '/integritetspolicy'
    | '/intervjusvar'
    | '/jobbsokare'
    | '/kommuner'
    | '/messages'
    | '/migrate-media'
    | '/my-applications'
    | '/my-candidates'
    | '/my-jobs'
    | '/om-oss'
    | '/payment'
    | '/profile'
    | '/profile-preview'
    | '/reports'
    | '/reset-redirect'
    | '/reviews'
    | '/saved-jobs'
    | '/search-jobs'
    | '/settings'
    | '/status'
    | '/subscription'
    | '/support'
    | '/team-invite'
    | '/templates'
    | '/unsubscribe'
    | '/valj-plan'
    | '/verify'
    | '/yrken'
    | '/annons/$jobId'
    | '/guider/$slug'
    | '/guider/cv-mall-2026'
    | '/job-application/$jobId'
    | '/job-details/$jobId'
    | '/job-view/$jobId'
    | '/job/$jobId'
    | '/kommun/$kommunSlug'
    | '/yrke/$occupationSlug'
    | '/guider/'
    | '/jobb/'
    | '/.lovable/oauth/consent'
    | '/jobb/$citySlug/$occupationSlug'
    | '/oauth/$connector/return'
    | '/jobb/$citySlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/ai-usage'
    | '/annonser'
    | '/arbetsgivare'
    | '/auth'
    | '/billing'
    | '/candidates'
    | '/checkout'
    | '/company-profile'
    | '/confirm'
    | '/cv-tunnel'
    | '/dashboard'
    | '/dpa'
    | '/email-confirm'
    | '/email-redirect'
    | '/employer-profile'
    | '/home'
    | '/integritetspolicy'
    | '/intervjusvar'
    | '/jobbsokare'
    | '/kommuner'
    | '/messages'
    | '/migrate-media'
    | '/my-applications'
    | '/my-candidates'
    | '/my-jobs'
    | '/om-oss'
    | '/payment'
    | '/profile'
    | '/profile-preview'
    | '/reports'
    | '/reset-redirect'
    | '/reviews'
    | '/saved-jobs'
    | '/search-jobs'
    | '/settings'
    | '/status'
    | '/subscription'
    | '/support'
    | '/team-invite'
    | '/templates'
    | '/unsubscribe'
    | '/valj-plan'
    | '/verify'
    | '/yrken'
    | '/annons/$jobId'
    | '/guider/$slug'
    | '/guider/cv-mall-2026'
    | '/job-application/$jobId'
    | '/job-details/$jobId'
    | '/job-view/$jobId'
    | '/job/$jobId'
    | '/kommun/$kommunSlug'
    | '/yrke/$occupationSlug'
    | '/guider'
    | '/jobb'
    | '/.lovable/oauth/consent'
    | '/jobb/$citySlug/$occupationSlug'
    | '/oauth/$connector/return'
    | '/jobb/$citySlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/ai-usage'
    | '/annonser'
    | '/arbetsgivare'
    | '/auth'
    | '/billing'
    | '/candidates'
    | '/checkout'
    | '/company-profile'
    | '/confirm'
    | '/cv-tunnel'
    | '/dashboard'
    | '/dpa'
    | '/email-confirm'
    | '/email-redirect'
    | '/employer-profile'
    | '/home'
    | '/integritetspolicy'
    | '/intervjusvar'
    | '/jobbsokare'
    | '/kommuner'
    | '/messages'
    | '/migrate-media'
    | '/my-applications'
    | '/my-candidates'
    | '/my-jobs'
    | '/om-oss'
    | '/payment'
    | '/profile'
    | '/profile-preview'
    | '/reports'
    | '/reset-redirect'
    | '/reviews'
    | '/saved-jobs'
    | '/search-jobs'
    | '/settings'
    | '/status'
    | '/subscription'
    | '/support'
    | '/team-invite'
    | '/templates'
    | '/unsubscribe'
    | '/valj-plan'
    | '/verify'
    | '/yrken'
    | '/annons/$jobId'
    | '/guider/$slug'
    | '/guider/cv-mall-2026'
    | '/job-application/$jobId'
    | '/job-details/$jobId'
    | '/job-view/$jobId'
    | '/job/$jobId'
    | '/kommun/$kommunSlug'
    | '/yrke/$occupationSlug'
    | '/guider/'
    | '/jobb/'
    | '/.lovable/oauth/consent'
    | '/jobb/$citySlug/$occupationSlug'
    | '/oauth/$connector/return'
    | '/jobb/$citySlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AiUsageRoute: typeof AiUsageRoute
  AnnonserRoute: typeof AnnonserRoute
  ArbetsgivareRoute: typeof ArbetsgivareRoute
  AuthRoute: typeof AuthRoute
  BillingRoute: typeof BillingRoute
  CandidatesRoute: typeof CandidatesRoute
  CheckoutRoute: typeof CheckoutRoute
  CompanyProfileRoute: typeof CompanyProfileRoute
  ConfirmRoute: typeof ConfirmRoute
  CvTunnelRoute: typeof CvTunnelRoute
  DashboardRoute: typeof DashboardRoute
  DpaRoute: typeof DpaRoute
  EmailConfirmRoute: typeof EmailConfirmRoute
  EmailRedirectRoute: typeof EmailRedirectRoute
  EmployerProfileRoute: typeof EmployerProfileRoute
  HomeRoute: typeof HomeRoute
  IntegritetspolicyRoute: typeof IntegritetspolicyRoute
  IntervjusvarRoute: typeof IntervjusvarRoute
  JobbsokareRoute: typeof JobbsokareRoute
  KommunerRoute: typeof KommunerRoute
  MessagesRoute: typeof MessagesRoute
  MigrateMediaRoute: typeof MigrateMediaRoute
  MyApplicationsRoute: typeof MyApplicationsRoute
  MyCandidatesRoute: typeof MyCandidatesRoute
  MyJobsRoute: typeof MyJobsRoute
  OmOssRoute: typeof OmOssRoute
  PaymentRoute: typeof PaymentRoute
  ProfileRoute: typeof ProfileRoute
  ProfilePreviewRoute: typeof ProfilePreviewRoute
  ReportsRoute: typeof ReportsRoute
  ResetRedirectRoute: typeof ResetRedirectRoute
  ReviewsRoute: typeof ReviewsRoute
  SavedJobsRoute: typeof SavedJobsRoute
  SearchJobsRoute: typeof SearchJobsRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  SubscriptionRoute: typeof SubscriptionRoute
  SupportRoute: typeof SupportRoute
  TeamInviteRoute: typeof TeamInviteRoute
  TemplatesRoute: typeof TemplatesRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  ValjPlanRoute: typeof ValjPlanRoute
  VerifyRoute: typeof VerifyRoute
  YrkenRoute: typeof YrkenRoute
  AnnonsJobIdRoute: typeof AnnonsJobIdRoute
  GuiderSlugRoute: typeof GuiderSlugRoute
  GuiderCvMall2026Route: typeof GuiderCvMall2026Route
  JobApplicationJobIdRoute: typeof JobApplicationJobIdRoute
  JobDetailsJobIdRoute: typeof JobDetailsJobIdRoute
  JobViewJobIdRoute: typeof JobViewJobIdRoute
  JobJobIdRoute: typeof JobJobIdRoute
  KommunKommunSlugRoute: typeof KommunKommunSlugRoute
  YrkeOccupationSlugRoute: typeof YrkeOccupationSlugRoute
  GuiderIndexRoute: typeof GuiderIndexRoute
  JobbIndexRoute: typeof JobbIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  JobbCitySlugOccupationSlugRoute: typeof JobbCitySlugOccupationSlugRoute
  OauthConnectorReturnRoute: typeof OauthConnectorReturnRoute
  JobbCitySlugIndexRoute: typeof JobbCitySlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-usage': {
      id: '/ai-usage'
      path: '/ai-usage'
      fullPath: '/ai-usage'
      preLoaderRoute: typeof AiUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonser': {
      id: '/annonser'
      path: '/annonser'
      fullPath: '/annonser'
      preLoaderRoute: typeof AnnonserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arbetsgivare': {
      id: '/arbetsgivare'
      path: '/arbetsgivare'
      fullPath: '/arbetsgivare'
      preLoaderRoute: typeof ArbetsgivareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company-profile': {
      id: '/company-profile'
      path: '/company-profile'
      fullPath: '/company-profile'
      preLoaderRoute: typeof CompanyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirm': {
      id: '/confirm'
      path: '/confirm'
      fullPath: '/confirm'
      preLoaderRoute: typeof ConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv-tunnel': {
      id: '/cv-tunnel'
      path: '/cv-tunnel'
      fullPath: '/cv-tunnel'
      preLoaderRoute: typeof CvTunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dpa': {
      id: '/dpa'
      path: '/dpa'
      fullPath: '/dpa'
      preLoaderRoute: typeof DpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-confirm': {
      id: '/email-confirm'
      path: '/email-confirm'
      fullPath: '/email-confirm'
      preLoaderRoute: typeof EmailConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email-redirect': {
      id: '/email-redirect'
      path: '/email-redirect'
      fullPath: '/email-redirect'
      preLoaderRoute: typeof EmailRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer-profile': {
      id: '/employer-profile'
      path: '/employer-profile'
      fullPath: '/employer-profile'
      preLoaderRoute: typeof EmployerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integritetspolicy': {
      id: '/integritetspolicy'
      path: '/integritetspolicy'
      fullPath: '/integritetspolicy'
      preLoaderRoute: typeof IntegritetspolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intervjusvar': {
      id: '/intervjusvar'
      path: '/intervjusvar'
      fullPath: '/intervjusvar'
      preLoaderRoute: typeof IntervjusvarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobbsokare': {
      id: '/jobbsokare'
      path: '/jobbsokare'
      fullPath: '/jobbsokare'
      preLoaderRoute: typeof JobbsokareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kommuner': {
      id: '/kommuner'
      path: '/kommuner'
      fullPath: '/kommuner'
      preLoaderRoute: typeof KommunerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrate-media': {
      id: '/migrate-media'
      path: '/migrate-media'
      fullPath: '/migrate-media'
      preLoaderRoute: typeof MigrateMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-applications': {
      id: '/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof MyApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-candidates': {
      id: '/my-candidates'
      path: '/my-candidates'
      fullPath: '/my-candidates'
      preLoaderRoute: typeof MyCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-jobs': {
      id: '/my-jobs'
      path: '/my-jobs'
      fullPath: '/my-jobs'
      preLoaderRoute: typeof MyJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/om-oss': {
      id: '/om-oss'
      path: '/om-oss'
      fullPath: '/om-oss'
      preLoaderRoute: typeof OmOssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-preview': {
      id: '/profile-preview'
      path: '/profile-preview'
      fullPath: '/profile-preview'
      preLoaderRoute: typeof ProfilePreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-redirect': {
      id: '/reset-redirect'
      path: '/reset-redirect'
      fullPath: '/reset-redirect'
      preLoaderRoute: typeof ResetRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-jobs': {
      id: '/saved-jobs'
      path: '/saved-jobs'
      fullPath: '/saved-jobs'
      preLoaderRoute: typeof SavedJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-jobs': {
      id: '/search-jobs'
      path: '/search-jobs'
      fullPath: '/search-jobs'
      preLoaderRoute: typeof SearchJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team-invite': {
      id: '/team-invite'
      path: '/team-invite'
      fullPath: '/team-invite'
      preLoaderRoute: typeof TeamInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valj-plan': {
      id: '/valj-plan'
      path: '/valj-plan'
      fullPath: '/valj-plan'
      preLoaderRoute: typeof ValjPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yrken': {
      id: '/yrken'
      path: '/yrken'
      fullPath: '/yrken'
      preLoaderRoute: typeof YrkenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annons/$jobId': {
      id: '/annons/$jobId'
      path: '/annons/$jobId'
      fullPath: '/annons/$jobId'
      preLoaderRoute: typeof AnnonsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/': {
      id: '/guider/'
      path: '/guider'
      fullPath: '/guider/'
      preLoaderRoute: typeof GuiderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/$slug': {
      id: '/guider/$slug'
      path: '/guider/$slug'
      fullPath: '/guider/$slug'
      preLoaderRoute: typeof GuiderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guider/cv-mall-2026': {
      id: '/guider/cv-mall-2026'
      path: '/guider/cv-mall-2026'
      fullPath: '/guider/cv-mall-2026'
      preLoaderRoute: typeof GuiderCvMall2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-application/$jobId': {
      id: '/job-application/$jobId'
      path: '/job-application/$jobId'
      fullPath: '/job-application/$jobId'
      preLoaderRoute: typeof JobApplicationJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-details/$jobId': {
      id: '/job-details/$jobId'
      path: '/job-details/$jobId'
      fullPath: '/job-details/$jobId'
      preLoaderRoute: typeof JobDetailsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-view/$jobId': {
      id: '/job-view/$jobId'
      path: '/job-view/$jobId'
      fullPath: '/job-view/$jobId'
      preLoaderRoute: typeof JobViewJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job/$jobId': {
      id: '/job/$jobId'
      path: '/job/$jobId'
      fullPath: '/job/$jobId'
      preLoaderRoute: typeof JobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobb/': {
      id: '/jobb/'
      path: '/jobb'
      fullPath: '/jobb/'
      preLoaderRoute: typeof JobbIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kommun/$kommunSlug': {
      id: '/kommun/$kommunSlug'
      path: '/kommun/$kommunSlug'
      fullPath: '/kommun/$kommunSlug'
      preLoaderRoute: typeof KommunKommunSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yrke/$occupationSlug': {
      id: '/yrke/$occupationSlug'
      path: '/yrke/$occupationSlug'
      fullPath: '/yrke/$occupationSlug'
      preLoaderRoute: typeof YrkeOccupationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobb/$citySlug/': {
      id: '/jobb/$citySlug/'
      path: '/jobb/$citySlug'
      fullPath: '/jobb/$citySlug/'
      preLoaderRoute: typeof JobbCitySlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobb/$citySlug/$occupationSlug': {
      id: '/jobb/$citySlug/$occupationSlug'
      path: '/jobb/$citySlug/$occupationSlug'
      fullPath: '/jobb/$citySlug/$occupationSlug'
      preLoaderRoute: typeof JobbCitySlugOccupationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/$connector/return': {
      id: '/oauth/$connector/return'
      path: '/oauth/$connector/return'
      fullPath: '/oauth/$connector/return'
      preLoaderRoute: typeof OauthConnectorReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AiUsageRoute: AiUsageRoute,
  AnnonserRoute: AnnonserRoute,
  ArbetsgivareRoute: ArbetsgivareRoute,
  AuthRoute: AuthRoute,
  BillingRoute: BillingRoute,
  CandidatesRoute: CandidatesRoute,
  CheckoutRoute: CheckoutRoute,
  CompanyProfileRoute: CompanyProfileRoute,
  ConfirmRoute: ConfirmRoute,
  CvTunnelRoute: CvTunnelRoute,
  DashboardRoute: DashboardRoute,
  DpaRoute: DpaRoute,
  EmailConfirmRoute: EmailConfirmRoute,
  EmailRedirectRoute: EmailRedirectRoute,
  EmployerProfileRoute: EmployerProfileRoute,
  HomeRoute: HomeRoute,
  IntegritetspolicyRoute: IntegritetspolicyRoute,
  IntervjusvarRoute: IntervjusvarRoute,
  JobbsokareRoute: JobbsokareRoute,
  KommunerRoute: KommunerRoute,
  MessagesRoute: MessagesRoute,
  MigrateMediaRoute: MigrateMediaRoute,
  MyApplicationsRoute: MyApplicationsRoute,
  MyCandidatesRoute: MyCandidatesRoute,
  MyJobsRoute: MyJobsRoute,
  OmOssRoute: OmOssRoute,
  PaymentRoute: PaymentRoute,
  ProfileRoute: ProfileRoute,
  ProfilePreviewRoute: ProfilePreviewRoute,
  ReportsRoute: ReportsRoute,
  ResetRedirectRoute: ResetRedirectRoute,
  ReviewsRoute: ReviewsRoute,
  SavedJobsRoute: SavedJobsRoute,
  SearchJobsRoute: SearchJobsRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  SubscriptionRoute: SubscriptionRoute,
  SupportRoute: SupportRoute,
  TeamInviteRoute: TeamInviteRoute,
  TemplatesRoute: TemplatesRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  ValjPlanRoute: ValjPlanRoute,
  VerifyRoute: VerifyRoute,
  YrkenRoute: YrkenRoute,
  AnnonsJobIdRoute: AnnonsJobIdRoute,
  GuiderSlugRoute: GuiderSlugRoute,
  GuiderCvMall2026Route: GuiderCvMall2026Route,
  JobApplicationJobIdRoute: JobApplicationJobIdRoute,
  JobDetailsJobIdRoute: JobDetailsJobIdRoute,
  JobViewJobIdRoute: JobViewJobIdRoute,
  JobJobIdRoute: JobJobIdRoute,
  KommunKommunSlugRoute: KommunKommunSlugRoute,
  YrkeOccupationSlugRoute: YrkeOccupationSlugRoute,
  GuiderIndexRoute: GuiderIndexRoute,
  JobbIndexRoute: JobbIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  JobbCitySlugOccupationSlugRoute: JobbCitySlugOccupationSlugRoute,
  OauthConnectorReturnRoute: OauthConnectorReturnRoute,
  JobbCitySlugIndexRoute: JobbCitySlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
