// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.28.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.83.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/whoami.ts
var whoami_default = defineTool({
  name: "whoami",
  title: "Vem \xE4r inloggad",
  description: "H\xE4mtar den inloggade anv\xE4ndarens Parium-profil (namn, roll, ort, f\xF6retag).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select("user_id, first_name, last_name, role, occupation, location, company_name, onboarding_completed").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Ingen profil hittades." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/search-jobs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z } from "npm:zod@^4.5.1";
var JOB_FIELDS = "id, title, occupation, category, employment_type, location, workplace_city, workplace_municipality, workplace_county, work_location_type, remote_work_possible, salary_min, salary_max, salary_type, published_at, expires_at";
var search_jobs_default = defineTool2({
  name: "search_jobs",
  title: "S\xF6k jobb",
  description: "S\xF6ker bland aktiva jobbannonser p\xE5 Parium efter titel, yrke eller ort.",
  inputSchema: {
    query: z.string().optional().describe("Fritext som matchas mot annonsens titel eller yrke."),
    city: z.string().optional().describe("Ort eller kommun att filtrera p\xE5."),
    limit: z.number().int().optional().describe("Max antal tr\xE4ffar, 1\u201350. Standard 10.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, city, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
    }
    const take = Math.min(50, Math.max(1, Math.trunc(limit ?? 10)));
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("job_postings").select(JOB_FIELDS).eq("is_active", true).is("deleted_at", null).order("published_at", { ascending: false }).limit(take);
    const trimmedQuery = query?.trim();
    if (trimmedQuery) {
      const like = `%${trimmedQuery.replace(/[%,]/g, " ")}%`;
      request = request.or(`title.ilike.${like},occupation.ilike.${like}`);
    }
    const trimmedCity = city?.trim();
    if (trimmedCity) {
      const like = `%${trimmedCity.replace(/[%,]/g, " ")}%`;
      request = request.or(
        `workplace_city.ilike.${like},workplace_municipality.ilike.${like},location.ilike.${like}`
      );
    }
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-job.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z2 } from "npm:zod@^4.5.1";
var get_job_default = defineTool3({
  name: "get_job",
  title: "H\xE4mta jobbannons",
  description: "H\xE4mtar detaljer om en jobbannons p\xE5 Parium via dess id.",
  inputSchema: {
    job_id: z2.string().describe("Annonsens id (uuid).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ job_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("job_postings").select(
      "id, title, pitch, description, requirements, benefits, occupation, category, employment_type, work_schedule, work_location_type, remote_work_possible, location, workplace_name, workplace_city, workplace_municipality, workplace_county, salary_min, salary_max, salary_type, salary_transparency, positions_count, start_date, published_at, expires_at, is_active"
    ).eq("id", job_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Annonsen hittades inte." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { job: data }
    };
  }
});

// src/lib/mcp/tools/list-my-job-postings.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z3 } from "npm:zod@^4.5.1";
var list_my_job_postings_default = defineTool4({
  name: "list_my_job_postings",
  title: "Mina jobbannonser",
  description: "Listar den inloggade arbetsgivarens egna jobbannonser med antal ans\xF6kningar och visningar.",
  inputSchema: {
    only_active: z3.boolean().optional().describe("Visa endast aktiva annonser. Standard false."),
    limit: z3.number().int().optional().describe("Max antal annonser, 1\u2013100. Standard 20.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ only_active, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
    }
    const take = Math.min(100, Math.max(1, Math.trunc(limit ?? 20)));
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("job_postings").select(
      "id, title, occupation, location, is_active, applications_count, views_count, published_at, expires_at, created_at"
    ).eq("employer_id", ctx.getUserId()).is("deleted_at", null).order("created_at", { ascending: false }).limit(take);
    if (only_active) request = request.eq("is_active", true);
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-job-applications.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z4 } from "npm:zod@^4.5.1";
var list_job_applications_default = defineTool5({
  name: "list_job_applications",
  title: "Ans\xF6kningar till en annons",
  description: "Listar ans\xF6kningar till en av arbetsgivarens egna jobbannonser.",
  inputSchema: {
    job_id: z4.string().describe("Annonsens id (uuid)."),
    status: z4.string().optional().describe("Filtrera p\xE5 status, till exempel pending eller interview."),
    limit: z4.number().int().optional().describe("Max antal ans\xF6kningar, 1\u2013100. Standard 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ job_id, status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
    }
    const take = Math.min(100, Math.max(1, Math.trunc(limit ?? 25)));
    const supabase = supabaseForUser(ctx);
    let request = supabase.from("job_applications").select(
      "id, job_id, status, first_name, last_name, location, occupation:employment_status, availability, work_schedule, applied_at, viewed_at"
    ).eq("job_id", job_id).order("applied_at", { ascending: false }).limit(take);
    if (status?.trim()) request = request.eq("status", status.trim());
    const { data, error } = await request;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { applications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-applications.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.28.0";
import { z as z5 } from "npm:zod@^4.5.1";
var list_my_applications_default = defineTool6({
  name: "list_my_applications",
  title: "Mina ans\xF6kningar",
  description: "Listar den inloggade jobbs\xF6karens egna ans\xF6kningar och deras status.",
  inputSchema: {
    limit: z5.number().int().optional().describe("Max antal ans\xF6kningar, 1\u2013100. Standard 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Inte inloggad." }], isError: true };
    }
    const take = Math.min(100, Math.max(1, Math.trunc(limit ?? 25)));
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("job_applications").select("id, job_id, status, applied_at, updated_at, candidate_profile_label").eq("applicant_id", ctx.getUserId()).order("applied_at", { ascending: false }).limit(take);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { applications: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jrjaegapuujushsiofoi";
var mcp_default = defineMcp({
  name: "parium-ab",
  title: "parium-ab",
  version: "0.1.0",
  instructions: "Verktyg f\xF6r Parium \u2014 svensk jobbplattform. S\xF6k jobb, h\xE4mta annonsdetaljer, se dina egna annonser och ans\xF6kningar. Alla verktyg k\xF6rs som den inloggade anv\xE4ndaren och respekterar plattformens beh\xF6righeter.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    search_jobs_default,
    get_job_default,
    list_my_job_postings_default,
    list_job_applications_default,
    list_my_applications_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.28.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
