ALTER POLICY "Employers can create evaluations for their jobs" ON public.candidate_evaluations TO authenticated;
ALTER POLICY "Employers can update evaluations for their jobs" ON public.candidate_evaluations TO authenticated;
ALTER POLICY "Employers can view evaluations for their jobs" ON public.candidate_evaluations TO authenticated;
ALTER POLICY "Employers can create summaries for their jobs" ON public.candidate_summaries TO authenticated;
ALTER POLICY "Employers can update summaries for their jobs" ON public.candidate_summaries TO authenticated;
ALTER POLICY "Employers can view summaries for their jobs" ON public.candidate_summaries TO authenticated;
ALTER POLICY "Users can view conversation members" ON public.conversation_members TO authenticated;
ALTER POLICY "Employers can insert criterion results" ON public.criterion_results TO authenticated;
ALTER POLICY "Employers can update criterion results" ON public.criterion_results TO authenticated;
ALTER POLICY "Employers can view criterion results" ON public.criterion_results TO authenticated;
ALTER POLICY "Employers can update applications to org jobs" ON public.job_applications TO authenticated;
ALTER POLICY "Employers can view applications to org jobs" ON public.job_applications TO authenticated;
ALTER POLICY "Employers can delete criteria for their jobs" ON public.job_criteria TO authenticated;
ALTER POLICY "Employers can update criteria for their jobs" ON public.job_criteria TO authenticated;
ALTER POLICY "Employers can view criteria for their jobs" ON public.job_criteria TO authenticated;
ALTER POLICY "Employers can create job stage settings" ON public.job_stage_settings TO authenticated;
ALTER POLICY "Employers can delete job stage settings" ON public.job_stage_settings TO authenticated;
ALTER POLICY "Employers can update job stage settings" ON public.job_stage_settings TO authenticated;
ALTER POLICY "Employers can view their job stage settings" ON public.job_stage_settings TO authenticated;