// This file is automatically generated. Do not edit it directly.
// NOTE: Lazy-initialized below so module evaluation performs no async I/O,
// timers or storage access — required for Cloudflare Workers SSR, where such
// work in global scope throws "Disallowed operation called within global scope".
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { authStorage } from '@/lib/authStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof window !== 'undefined' && typeof document !== 'undefined';

let cachedClient: SupabaseClient<Database> | null = null;

function getSupabaseClient(): SupabaseClient<Database> {
  if (!cachedClient) {
    cachedClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: isBrowser
        ? {
            storage: authStorage,
            persistSession: true,
            autoRefreshToken: true,
          }
        : {
            // SSR (Workers): ingen browser-lagring eller token-timers finns.
            persistSession: false,
            autoRefreshToken: false,
          },
    });
  }
  return cachedClient;
}

/**
 * Lazy proxy — skapar klienten först vid första användning (i render-/request-
 * scope) i stället för vid modulimport. Publikt API är identiskt med tidigare:
 * supabase.auth…, supabase.from(…), supabase.rpc(…), supabase.functions… osv.
 */
export const supabase: SupabaseClient<Database> = new Proxy(
  {} as SupabaseClient<Database>,
  {
    get(_target, prop, _receiver) {
      const client = getSupabaseClient() as unknown as Record<PropertyKey, unknown>;
      const value = client[prop];
      return typeof value === 'function' ? (value as (...args: unknown[]) => unknown).bind(client) : value;
    },
    set(_target, prop, value) {
      const client = getSupabaseClient() as unknown as Record<PropertyKey, unknown>;
      client[prop] = value;
      return true;
    },
    has(_target, prop) {
      return prop in getSupabaseClient();
    },
  },
);
